import type { Language, Translations } from "./types";

type DeepPartial<T> = { [K in keyof T]?: T[K] extends Array<infer U> ? U[] : T[K] extends object ? DeepPartial<T[K]> : T[K] };

export const contentRestructure: Record<Language, DeepPartial<Translations>> = {
  de: {
    home: {
      heroTitle: "Immobilien einfach und direkt lösen – in Deutschland und in der Türkei.",
      heroDescription: "Wir kaufen Immobilien in Deutschland auf eigene Rechnung und begleiten besondere Verkaufssituationen. Für Eigentümer mit Immobilien in der Türkei sind wir die persönliche Anlaufstelle in Deutschland – mit erfahrenen Partnern vor Ort.",
      heroPrimaryCta: "Immobilie anbieten", heroSecondaryCta: "Unsere Bereiche", heroTrustLine: "Direkt · Diskret · Persönlich in Deutschland und der Türkei",
      areasTitle: "Wo befindet sich Ihre Immobilie?", areasIntro: "Wählen Sie den passenden Einstieg. Wir prüfen Ihre Anfrage persönlich, diskret und unverbindlich.",
      areas: [
        { title: "Immobilie in Deutschland", desc: "Sie möchten eine Immobilie direkt verkaufen oder befinden sich in einer besonderen Situation? Wir prüfen Ihr Objekt persönlich, diskret und unverbindlich.", cta: "Immobilie in Deutschland anbieten" },
        { title: "Immobilie in der Türkei", desc: "Sie leben in Deutschland oder Europa und möchten eine Wohnung, ein Haus oder Grundstück in der Türkei verkaufen? Sprechen Sie zuerst mit uns in Deutschland.", cta: "Immobilie in der Türkei anbieten" },
      ],
      trustTitle: "Direkte, diskrete und strukturierte Immobilienlösungen", trustText: "Je nach Objekt kauft Aurelia selbst an oder strukturiert die Abwicklung mit ausgewählten Partnern. Entscheidungen treffen wir nachvollziehbar und ohne pauschale Versprechen.",
      stepsTitle: "So beginnt Ihre Anfrage", steps: [
        { title: "Bereich wählen", desc: "Teilen Sie uns mit, ob sich Ihre Immobilie in Deutschland oder in der Türkei befindet." },
        { title: "Objekt und Situation prüfen", desc: "Wir sichten die Angaben und besprechen Ihre persönliche Ausgangslage." },
        { title: "Passenden Weg festlegen", desc: "Sie erhalten eine klare Einschätzung zum direkten Ankauf oder zu einer strukturierten Abwicklung." },
      ],
      stepsNote: "Die Prüfung ist unverbindlich. Welche Lösung möglich ist, hängt vom Objekt, den Beteiligten und den geltenden Rahmenbedingungen ab.",
      finalCtaTitle: "Welche Immobilie möchten Sie mit uns besprechen?", finalCtaText: "Beginnen Sie mit wenigen Angaben. Wir melden uns persönlich und vertraulich.", finalCtaButton: "Immobilie anbieten",
    },
    ownerInTrouble: {
      heroKicker: "Für Eigentümer in Deutschland", heroTitle: "Direkte Lösungen für Immobilien und Grundstücke.", heroDescription: "Ob regulärer Direktverkauf, Leerstand, Renovierungsbedarf oder eine komplexe und zeitkritische Situation: Aurelia prüft Immobilien in Deutschland persönlich, diskret und auf eigene Rechnung.", heroPrimaryCta: "Immobilie in Deutschland anbieten", heroTrustLine: "Direkter Ankauf · Diskrete Prüfung · Klare Rückmeldung",
      situationsTitle: "Immobilienverkauf in unterschiedlichen Situationen", situationsIntro: "Nicht jeder Verkauf folgt demselben Weg. Wir prüfen sowohl klassische Direktverkäufe als auch besondere Konstellationen.",
      situations: [
        { title: "Direkter Verkaufswunsch", desc: "Verkauf ohne öffentliche Vermarktung, Besichtigungsmarathon oder Maklerprovision." },
        { title: "Leerstand oder Renovierungsbedarf", desc: "Auch Objekte mit Instandhaltungsbedarf oder ungeklärter weiterer Nutzung prüfen wir individuell." },
        { title: "Mehrere Eigentümer oder Erbfall", desc: "Bei Erbengemeinschaften und mehreren Beteiligten ordnen wir die Ausgangslage strukturiert ein." },
        { title: "Komplexe oder zeitkritische Lage", desc: "Finanzielle Belastung, schwierige Mietverhältnisse oder ein laufendes Verfahren können eine schnelle, klare Prüfung erfordern." },
      ],
      solutionTitle: "Direkter Ankauf statt Standardprozess", solutionText: "Wir kaufen geeignete Immobilien und Grundstücke selbst. Sie sprechen mit den Personen, die prüfen und entscheiden – persönlich, nachvollziehbar und vertraulich.",
      finalCtaTitle: "Immobilie in Deutschland anbieten", finalCtaText: "Senden Sie uns die wichtigsten Angaben. Wir prüfen Objekt und Ausgangslage unverbindlich.", finalCtaButton: "Anfrage starten",
    },
    howItWorks: {
      heroDescription: "Aurelia verbindet direkten Immobilienankauf in Deutschland, Immobilienlösungen in der Türkei sowie Verkauf aus eigenem Bestand und projektbezogene Kooperationen.",
      introTitle: "Drei Geschäftsbereiche, ein gemeinsames Prinzip", introText: "Wir prüfen persönlich, kommunizieren klar und wählen den Weg, der zum Objekt und zur konkreten Ausgangssituation passt.",
      segmentsTitle: "Unsere drei Geschäftsbereiche", segmentsIntro: "Deutschland und Türkei werden mit klaren Ansprechpartnern und nachvollziehbaren Abläufen verbunden.",
      segments: [
        { title: "Direkter Immobilienankauf", desc: "Immobilien und Grundstücke in Deutschland – auch bei komplexen oder zeitkritischen Situationen. Aurelia prüft und kauft geeignete Objekte auf eigene Rechnung." },
        { title: "Immobilien in der Türkei", desc: "Prüfung, möglicher Ankauf oder strukturierte Abwicklung für Eigentümer mit Lebensmittelpunkt in Deutschland oder Europa – gemeinsam mit geeigneten Partnern vor Ort." },
        { title: "Verkauf & Kooperationen", desc: "Verkauf ausgewählter Immobilien aus dem eigenen Bestand sowie Zusammenarbeit mit Investoren, Projektentwicklern und ausgewählten Partnern." },
      ],
      holdTitle: "Vom Erstkontakt zur passenden Lösung", holdIntro: "Der konkrete Ablauf richtet sich nach Geschäftsbereich, Objekt und Beteiligten.",
      holdSteps: [
        { title: "Anfrage", desc: "Sie übermitteln die wichtigsten Angaben zu Objekt und Ziel." }, { title: "Prüfung", desc: "Wir sichten Unterlagen, Ausgangslage und wirtschaftliche Eckdaten." }, { title: "Gespräch", desc: "Offene Fragen und realistische Wege werden persönlich besprochen." }, { title: "Entscheidung", desc: "Wir klären direkten Ankauf, Bestandsverkauf oder Kooperation." }, { title: "Abwicklung", desc: "Verträge und weitere Schritte werden fallbezogen und nachvollziehbar koordiniert." },
      ],
      holdNote: "Bei rechtlichen, steuerlichen oder fachlichen Fragen werden bei Bedarf geeignete externe Berater eingebunden.",
    },
    partners: {
      heroTitle: "Kooperationen in Deutschland und der Türkei.", heroDescription: "Wir arbeiten projektbezogen mit Projektentwicklern, Immobilienunternehmen, Investoren, Maklern, lokalen Immobilienpartnern, Fachberatern, Rechtsanwälten und weiteren Spezialisten.",
      formsTitle: "Partner für unterschiedliche Aufgaben", formsIntro: "Jede Zusammenarbeit wird passend zu Land, Objekt und Verantwortungsbereich vereinbart.",
      forms: [
        { title: "Projektentwickler & Immobilienunternehmen", desc: "Kooperation bei Ankauf, Entwicklung, Bestand und Verkauf geeigneter Projekte." }, { title: "Investoren", desc: "Individuelle, projektbezogene Zusammenarbeit mit klar dokumentiertem Rahmen." }, { title: "Makler & lokale Immobilienpartner", desc: "Marktkenntnis, Objektzugang und koordinierte Umsetzung in Deutschland und der Türkei." }, { title: "Fachberater & Rechtsanwälte", desc: "Externe Spezialisten werden eingebunden, wenn der konkrete Fall fachliche oder rechtliche Begleitung erfordert." },
      ],
    },
    aboutV2: {
      seoDescription: "Aurelia Grundbesitz verbindet direkten Immobilienankauf in Deutschland mit grenzüberschreitender Immobilienkompetenz zwischen Deutschland und der Türkei.",
      hero: { body: ["Aurelia Grundbesitz verbindet direkten Immobilienankauf in Deutschland mit grenzüberschreitender Immobilienkompetenz zwischen Deutschland und der Türkei.", "Wir prüfen geeignete Immobilien auf eigene Rechnung, begleiten besondere Verkaufssituationen und strukturieren bei Türkei-Immobilien gemeinsam mit ausgewählten Partnern den passenden Weg.", "Unser Anspruch ist eine persönliche, nachvollziehbare und diskrete Abwicklung mit kurzen Entscheidungswegen." ] },
      approach: { headline: "Deutschland und Türkei verbunden", body: ["Für Immobilien in der Türkei greifen wir auf ein Netzwerk aus lokalen Immobilienpartnern, Fachberatern und Rechtsanwälten zurück.", "Dadurch können Eigentümer ihre Anfrage zunächst bequem aus Deutschland oder einem anderen europäischen Land an uns richten.", "Aurelia selbst bietet keine Rechts- oder Steuerberatung an. Geeignete externe Fachberater werden eingebunden, wenn der konkrete Fall dies erfordert."] },
      situations: { headline: "Unsere Märkte und Geschäftsbereiche", items: ["Immobilienankauf in Deutschland", "Immobilien in der Türkei für Eigentümer mit Lebensmittelpunkt in Deutschland oder Europa", "Verkauf ausgewählter Immobilien aus eigenem Bestand", "Projektbezogene Kooperationen in Deutschland und der Türkei", "Direkte, diskrete und strukturierte Prüfung", "Einbindung geeigneter lokaler Partner und Fachberater bei Bedarf"] },
    },
    faqPage: { intro: "Antworten zu Immobilien in Deutschland, in der Türkei, zu Ankauf, Verkauf und Zusammenarbeit.", items: [
      { q: "Ich lebe in Deutschland und besitze eine Immobilie in der Türkei – kann ich mich an Aurelia wenden?", a: "Ja. Ihre Anfrage beginnt bei uns in Deutschland. Wir prüfen Ihre Angaben und besprechen, welcher Weg für das Objekt sinnvoll sein kann." },
      { q: "Muss ich für die erste Prüfung in die Türkei reisen?", a: "Nein. Für die erste Einordnung können Sie Angaben und vorhandene Unterlagen online übermitteln. Ob später ein Termin vor Ort erforderlich ist, hängt vom Objekt und vom konkreten Fall ab." },
      { q: "Kauft Aurelia Immobilien in der Türkei selbst?", a: "In geeigneten Fällen prüfen wir einen direkten Ankauf. Wenn dieser nicht passt, kann eine strukturierte Vermarktungs- oder Abwicklungslösung mit ausgewählten Partnern vor Ort geprüft werden." },
      { q: "Kann auch ein Partner vor Ort den Verkauf übernehmen?", a: "Ja, wenn dies für den Fall sinnvoll ist. Aufgaben, Verantwortlichkeiten und die Einbindung externer Partner werden vorab transparent abgestimmt." },
      { q: "Wie läuft die Prüfung meiner Immobilie in der Türkei ab?", a: "Sie übermitteln Objektinformationen und vorhandene Unterlagen. Danach folgen eine erste Einschätzung, ein persönliches Gespräch und – falls nötig – eine Prüfung mit Partnern vor Ort." },
      { q: "Kann die Abwicklung auch erfolgen, wenn mehrere Eigentümer beteiligt sind?", a: "Grundsätzlich kann auch eine solche Konstellation geprüft werden. Entscheidend sind die Eigentumsverhältnisse, die Zustimmung der Beteiligten und die geltenden rechtlichen Rahmenbedingungen." },
      { q: "Wie wird die Vertrags- und Zahlungsabwicklung gestaltet?", a: "Sie richtet sich nach dem Objekt, den beteiligten Parteien und den geltenden rechtlichen Rahmenbedingungen. Geeignete externe Fachberater werden bei Bedarf eingebunden." },
    ] },
  },
  en: {
    home: { heroTitle: "Simple, direct property solutions – in Germany and Turkey.", heroDescription: "We purchase properties in Germany for our own account and support owners in particular selling situations. For property in Turkey, we are your personal contact in Germany, working with experienced local partners.", heroPrimaryCta: "Submit a property", heroSecondaryCta: "Our areas", heroTrustLine: "Direct · Discreet · Personal in Germany and Turkey", areasTitle: "Where is your property located?", areasIntro: "Choose the right starting point. We review your enquiry personally, discreetly and without obligation.", areas: [{ title: "Property in Germany", desc: "Would you like to sell directly or are you facing a particular situation? We review your property personally, discreetly and without obligation.", cta: "Submit a property in Germany" }, { title: "Property in Turkey", desc: "Do you live in Germany or Europe and want to sell an apartment, house or plot in Turkey? Speak to us in Germany first.", cta: "Submit a property in Turkey" }], trustTitle: "Direct, discreet and structured property solutions", trustText: "Depending on the property, Aurelia purchases directly or structures the process with selected partners. Our decisions are clear and never based on blanket promises.", stepsTitle: "How your enquiry starts", steps: [{ title: "Choose the area", desc: "Tell us whether your property is in Germany or Turkey." }, { title: "Review property and situation", desc: "We review your details and discuss your personal circumstances." }, { title: "Define the suitable route", desc: "You receive a clear view on a direct purchase or structured handling." }], stepsNote: "The review is non-binding. The available route depends on the property, the parties and the applicable framework.", finalCtaTitle: "Which property would you like to discuss?", finalCtaText: "Start with a few details. We will respond personally and confidentially.", finalCtaButton: "Submit a property" },
    ownerInTrouble: { heroKicker: "For owners in Germany", heroTitle: "Direct solutions for property and land.", heroDescription: "Whether a straightforward sale, vacancy, renovation needs or a complex and time-sensitive situation: Aurelia reviews property in Germany personally, discreetly and for its own account.", heroPrimaryCta: "Submit property in Germany", heroTrustLine: "Direct purchase · Discreet review · Clear response", situationsTitle: "Property sales in different situations", situationsIntro: "Not every sale follows the same route. We review conventional direct sales and particular circumstances alike.", situations: [{ title: "Direct sale", desc: "Sell without public marketing, repeated viewings or an estate agent's commission." }, { title: "Vacancy or renovation", desc: "We also review vacant properties and buildings requiring refurbishment." }, { title: "Several owners or inheritance", desc: "We structure the starting position where estates or several parties are involved." }, { title: "Complex or urgent situation", desc: "Financial pressure, difficult tenancies or ongoing proceedings may require a prompt, clear review." }], solutionTitle: "Direct purchase instead of a standard process", solutionText: "We purchase suitable property and land ourselves. You speak directly with the people reviewing and deciding your case.", finalCtaTitle: "Submit a property in Germany", finalCtaText: "Send us the key details. We review the property and situation without obligation.", finalCtaButton: "Start enquiry" },
    howItWorks: { heroDescription: "Aurelia combines direct property purchases in Germany, property solutions in Turkey, sales from its own portfolio and project-based cooperation.", introTitle: "Three business areas, one shared principle", introText: "We review personally, communicate clearly and choose a route suited to the property and its specific circumstances.", segmentsTitle: "Our three business areas", segmentsIntro: "Germany and Turkey are connected through clear contacts and transparent processes.", segments: [{ title: "Direct property purchase", desc: "Property and land in Germany, including complex or urgent situations. Aurelia reviews and purchases suitable assets for its own account." }, { title: "Property in Turkey", desc: "Review, possible purchase or structured handling for owners based in Germany or Europe, together with suitable local partners." }, { title: "Sales & cooperation", desc: "Sale of selected properties from our portfolio and cooperation with investors, developers and selected partners." }], holdTitle: "From first contact to the suitable solution", holdIntro: "The specific process depends on the business area, property and parties involved.", holdSteps: [{ title: "Enquiry", desc: "You provide the key facts about the property and your objective." }, { title: "Review", desc: "We examine documents, circumstances and economic facts." }, { title: "Conversation", desc: "We discuss open questions and realistic routes." }, { title: "Decision", desc: "We clarify direct purchase, portfolio sale or cooperation." }, { title: "Handling", desc: "Contracts and next steps are coordinated for the individual case." }], holdNote: "Suitable external advisers are involved where legal, tax or specialist questions require them." },
    partners: { heroTitle: "Cooperation in Germany and Turkey.", heroDescription: "We work on a project basis with developers, property companies, investors, agents, local property partners, professional advisers, lawyers and other specialists.", formsTitle: "Partners for different responsibilities", formsIntro: "Each cooperation is agreed to suit the country, property and responsibilities.", forms: [{ title: "Developers & property companies", desc: "Cooperation on acquisition, development, portfolio management and sale." }, { title: "Investors", desc: "Individual, project-based cooperation within a clearly documented framework." }, { title: "Agents & local partners", desc: "Market knowledge, property access and coordinated delivery in Germany and Turkey." }, { title: "Advisers & lawyers", desc: "External specialists are involved where the case requires professional or legal support." }] },
    aboutV2: { seoDescription: "Aurelia Grundbesitz combines direct property acquisition in Germany with cross-border expertise between Germany and Turkey.", hero: { body: ["Aurelia Grundbesitz combines direct property acquisition in Germany with cross-border property expertise between Germany and Turkey.", "We review suitable properties for our own account, support particular selling situations and work with selected partners to structure the right route for properties in Turkey.", "Our standard is a personal, transparent and discreet process with short decision paths."] }, approach: { headline: "Connecting Germany and Turkey", body: ["For property in Turkey, we draw on a network of local property partners, professional advisers and lawyers.", "Owners can therefore begin their enquiry conveniently from Germany or another European country.", "Aurelia does not provide legal or tax advice. Suitable external advisers are involved where required."] }, situations: { headline: "Our markets and business areas", items: ["Property acquisition in Germany", "Property in Turkey for owners based in Germany or Europe", "Sales of selected properties from our own portfolio", "Project-based cooperation in Germany and Turkey", "Direct, discreet and structured review", "Suitable local partners and advisers involved where required"] } },
    faqPage: { intro: "Answers about property in Germany and Turkey, purchasing, selling and cooperation.", items: [{ q: "I live in Germany and own property in Turkey. Can I contact Aurelia?", a: "Yes. Your enquiry starts with us in Germany. We review your details and discuss which route may suit the property." }, { q: "Do I need to travel to Turkey for the initial review?", a: "No. You can send details and available documents online. Whether a later visit is needed depends on the property and case." }, { q: "Does Aurelia purchase property in Turkey itself?", a: "In suitable cases we review a direct purchase. Otherwise, structured marketing or handling with selected local partners may be considered." }, { q: "Can a local partner handle the sale?", a: "Yes, where appropriate. Responsibilities and the involvement of external partners are agreed transparently in advance." }, { q: "How is my property in Turkey reviewed?", a: "You provide property details and documents. We then give an initial assessment, speak personally and, where needed, involve local partners." }, { q: "Can you handle a case with several owners?", a: "Such cases can generally be reviewed. Ownership, the parties' consent and the applicable legal framework are decisive." }, { q: "How are contracts and payments handled?", a: "This depends on the property, parties and applicable legal framework. Suitable external advisers are involved where necessary." }] },
  },
  tr: {
    home: { heroTitle: "Gayrimenkulleri kolay ve doğrudan çözüme kavuşturuyoruz – Almanya'da ve Türkiye'de.", heroDescription: "Almanya'daki gayrimenkulleri kendi hesabımıza satın alıyor, özel satış durumlarına eşlik ediyoruz. Türkiye'deki mülkler için Almanya'daki kişisel muhatabınızız ve yerel ortaklarla çalışıyoruz.", heroPrimaryCta: "Gayrimenkul sunun", areasTitle: "Gayrimenkulünüz nerede?", areasIntro: "Uygun başlangıç noktasını seçin. Talebinizi kişisel, gizli ve bağlayıcı olmadan inceleriz.", areas: [{ title: "Almanya'da gayrimenkul", desc: "Doğrudan satmak mı istiyorsunuz veya özel bir durumunuz mu var? Mülkünüzü kişisel ve gizli inceleriz.", cta: "Almanya'daki gayrimenkulü sunun" }, { title: "Türkiye'de gayrimenkul", desc: "Almanya'da veya Avrupa'da yaşıyor ve Türkiye'deki daire, ev ya da arsanızı satmak mı istiyorsunuz? Önce bizimle Almanya'da görüşün.", cta: "Türkiye'deki gayrimenkulü sunun" }] },
    ownerInTrouble: { heroKicker: "Almanya'daki mülk sahipleri için", heroTitle: "Gayrimenkul ve arsalar için doğrudan çözümler.", heroDescription: "Normal satış, boşluk, tadilat ihtiyacı veya karmaşık ve acil bir durum: Almanya'daki mülkleri kişisel, gizli ve kendi hesabımıza inceleriz.", situationsTitle: "Farklı durumlarda gayrimenkul satışı", solutionTitle: "Standart süreç yerine doğrudan alım" },
    howItWorks: { heroDescription: "Aurelia, Almanya'da doğrudan alımı, Türkiye'de gayrimenkul çözümlerini, kendi portföyünden satışları ve proje bazlı iş birliklerini birleştirir.", segmentsTitle: "Üç faaliyet alanımız", segments: [{ title: "Doğrudan gayrimenkul alımı", desc: "Almanya'daki gayrimenkul ve arsalar; karmaşık veya acil durumlar dahil." }, { title: "Türkiye'deki gayrimenkuller", desc: "Avrupa'da yaşayan maliklere inceleme, olası alım veya yerel ortaklarla yapılandırılmış işlem." }, { title: "Satış ve iş birlikleri", desc: "Kendi portföyümüzden satışlar ve yatırımcılar, geliştiriciler ve seçilmiş ortaklarla çalışma." }] },
    partners: { heroTitle: "Almanya ve Türkiye'de iş birlikleri.", heroDescription: "Proje geliştiriciler, gayrimenkul şirketleri, yatırımcılar, emlakçılar, yerel ortaklar, uzman danışmanlar ve avukatlarla proje bazında çalışıyoruz." },
    aboutV2: { seoDescription: "Aurelia Grundbesitz, Almanya'da doğrudan alımı Almanya ile Türkiye arasındaki sınır ötesi gayrimenkul uzmanlığıyla birleştirir.", approach: { headline: "Almanya ve Türkiye arasında bağlantı", body: ["Türkiye'deki gayrimenkuller için yerel emlak ortakları, uzman danışmanlar ve avukatlardan oluşan bir ağdan yararlanıyoruz.", "Malikler taleplerini Almanya'dan veya başka bir Avrupa ülkesinden başlatabilir.", "Aurelia hukuki veya vergisel danışmanlık sunmaz; gerektiğinde harici uzmanlar sürece dahil edilir."] }, situations: { headline: "Pazarlarımız ve faaliyet alanlarımız", items: ["Almanya'da gayrimenkul alımı", "Almanya veya Avrupa'da yaşayan maliklerin Türkiye'deki gayrimenkulleri", "Kendi portföyümüzden seçili gayrimenkullerin satışı", "Almanya ve Türkiye'de proje bazlı iş birlikleri", "Doğrudan, gizli ve yapılandırılmış inceleme", "Gerektiğinde uygun yerel ortaklar ve uzmanlar"] } },
  },
  nl: {
    home: { heroTitle: "Vastgoed eenvoudig en rechtstreeks oplossen – in Duitsland en Turkije.", heroDescription: "Wij kopen vastgoed in Duitsland voor eigen rekening. Voor vastgoed in Turkije zijn wij uw persoonlijke aanspreekpunt in Duitsland, samen met ervaren lokale partners.", areasTitle: "Waar bevindt uw vastgoed zich?", areasIntro: "Kies de passende ingang. Wij beoordelen uw aanvraag persoonlijk en vrijblijvend.", areas: [{ title: "Vastgoed in Duitsland", desc: "Wilt u rechtstreeks verkopen of bevindt u zich in een bijzondere situatie? Wij beoordelen uw vastgoed discreet.", cta: "Vastgoed in Duitsland aanbieden" }, { title: "Vastgoed in Turkije", desc: "Woont u in Duitsland of Europa en wilt u vastgoed in Turkije verkopen? Neem eerst contact met ons op in Duitsland.", cta: "Vastgoed in Turkije aanbieden" }] }, ownerInTrouble: { heroTitle: "Directe oplossingen voor vastgoed en grond.", heroDescription: "Van een gewone verkoop tot leegstand, renovatie of een complexe situatie: wij beoordelen vastgoed in Duitsland discreet en voor eigen rekening." }, howItWorks: { segmentsTitle: "Onze drie bedrijfsactiviteiten", segments: [{ title: "Directe vastgoedaankoop", desc: "Vastgoed en grond in Duitsland, ook bij complexe of urgente situaties." }, { title: "Vastgoed in Turkije", desc: "Beoordeling, mogelijke aankoop of gestructureerde afwikkeling voor eigenaren in Europa." }, { title: "Verkoop en samenwerking", desc: "Verkoop uit eigen portefeuille en samenwerking met investeerders, ontwikkelaars en partners." }] }, partners: { heroTitle: "Samenwerking in Duitsland en Turkije.", heroDescription: "Wij werken met ontwikkelaars, vastgoedbedrijven, investeerders, makelaars, lokale partners, adviseurs en advocaten." }, aboutV2: { approach: { headline: "Duitsland en Turkije verbinden", body: ["Voor vastgoed in Turkije werken wij met lokale vastgoedpartners, adviseurs en advocaten.", "Eigenaars kunnen hun aanvraag vanuit Duitsland of een ander Europees land starten.", "Aurelia geeft geen juridisch of fiscaal advies; waar nodig worden externe deskundigen betrokken."] }, situations: { headline: "Onze markten en activiteiten", items: ["Vastgoedaankoop in Duitsland", "Vastgoed in Turkije voor eigenaren in Duitsland of Europa", "Verkoop uit eigen portefeuille", "Projectgebonden samenwerking in Duitsland en Turkije", "Directe, discrete en gestructureerde beoordeling", "Lokale partners en adviseurs waar nodig"] } } },
  it: {
    home: { heroTitle: "Soluzioni immobiliari semplici e dirette – in Germania e in Turchia.", heroDescription: "Acquistiamo immobili in Germania per conto proprio. Per gli immobili in Turchia siamo il referente in Germania, con partner locali esperti.", areasTitle: "Dove si trova il suo immobile?", areasIntro: "Scelga il percorso adatto. Esaminiamo la richiesta personalmente e senza impegno.", areas: [{ title: "Immobile in Germania", desc: "Desidera vendere direttamente o si trova in una situazione particolare? Esaminiamo il suo immobile con discrezione.", cta: "Proporre un immobile in Germania" }, { title: "Immobile in Turchia", desc: "Vive in Germania o Europa e desidera vendere un immobile in Turchia? Si rivolga prima a noi in Germania.", cta: "Proporre un immobile in Turchia" }] }, ownerInTrouble: { heroTitle: "Soluzioni dirette per immobili e terreni.", heroDescription: "Dalla vendita diretta alla sfitta, alla ristrutturazione o a situazioni complesse: esaminiamo immobili in Germania con discrezione." }, howItWorks: { segmentsTitle: "Le nostre tre aree di attività", segments: [{ title: "Acquisto immobiliare diretto", desc: "Immobili e terreni in Germania, anche in situazioni complesse o urgenti." }, { title: "Immobili in Turchia", desc: "Verifica, possibile acquisto o gestione strutturata per proprietari in Europa." }, { title: "Vendita e collaborazioni", desc: "Vendita dal patrimonio e collaborazione con investitori, sviluppatori e partner." }] }, partners: { heroTitle: "Collaborazioni in Germania e Turchia.", heroDescription: "Collaboriamo con sviluppatori, società immobiliari, investitori, agenti, partner locali, consulenti e avvocati." }, aboutV2: { approach: { headline: "Collegare Germania e Turchia", body: ["Per gli immobili in Turchia ci avvaliamo di partner locali, consulenti e avvocati.", "I proprietari possono avviare la richiesta dalla Germania o da un altro paese europeo.", "Aurelia non presta consulenza legale o fiscale; se necessario coinvolgiamo professionisti esterni."] }, situations: { headline: "Mercati e attività", items: ["Acquisto immobiliare in Germania", "Immobili in Turchia per proprietari residenti in Germania o Europa", "Vendita di immobili selezionati dal patrimonio", "Collaborazioni progettuali in Germania e Turchia", "Valutazione diretta, riservata e strutturata", "Partner locali e consulenti quando necessario"] } } },
  es: {
    home: { heroTitle: "Soluciones inmobiliarias sencillas y directas – en Alemania y Turquía.", heroDescription: "Compramos inmuebles en Alemania por cuenta propia. Para inmuebles en Turquía somos su contacto en Alemania, con socios locales experimentados.", areasTitle: "¿Dónde se encuentra su inmueble?", areasIntro: "Elija el acceso adecuado. Revisamos su consulta personalmente y sin compromiso.", areas: [{ title: "Inmueble en Alemania", desc: "¿Desea vender directamente o está en una situación especial? Revisamos su inmueble con discreción.", cta: "Ofrecer inmueble en Alemania" }, { title: "Inmueble en Turquía", desc: "¿Vive en Alemania o Europa y desea vender un inmueble en Turquía? Hable primero con nosotros en Alemania.", cta: "Ofrecer inmueble en Turquía" }] }, ownerInTrouble: { heroTitle: "Soluciones directas para inmuebles y terrenos.", heroDescription: "Desde una venta directa hasta desocupación, reforma o situaciones complejas: revisamos inmuebles en Alemania con discreción." }, howItWorks: { segmentsTitle: "Nuestras tres áreas de actividad", segments: [{ title: "Compra inmobiliaria directa", desc: "Inmuebles y terrenos en Alemania, también en situaciones complejas o urgentes." }, { title: "Inmuebles en Turquía", desc: "Revisión, posible compra o gestión estructurada para propietarios en Europa." }, { title: "Venta y colaboraciones", desc: "Venta de cartera propia y colaboración con inversores, promotores y socios." }] }, partners: { heroTitle: "Colaboraciones en Alemania y Turquía.", heroDescription: "Colaboramos con promotores, empresas inmobiliarias, inversores, agentes, socios locales, asesores y abogados." }, aboutV2: { approach: { headline: "Conectamos Alemania y Turquía", body: ["Para inmuebles en Turquía contamos con socios locales, asesores y abogados.", "Los propietarios pueden iniciar su consulta desde Alemania u otro país europeo.", "Aurelia no presta asesoramiento jurídico o fiscal; incorporamos especialistas externos cuando es necesario."] }, situations: { headline: "Mercados y actividades", items: ["Compra de inmuebles en Alemania", "Inmuebles en Turquía para propietarios residentes en Alemania o Europa", "Venta de inmuebles seleccionados de cartera propia", "Cooperaciones por proyecto en Alemania y Turquía", "Evaluación directa, discreta y estructurada", "Socios locales y asesores cuando sea necesario"] } } },
  fr: {
    home: { heroTitle: "Des solutions immobilières simples et directes – en Allemagne et en Turquie.", heroDescription: "Nous achetons des biens en Allemagne pour notre propre compte. Pour les biens en Turquie, nous sommes votre interlocuteur en Allemagne, avec des partenaires locaux expérimentés.", areasTitle: "Où se trouve votre bien ?", areasIntro: "Choisissez le parcours adapté. Nous examinons votre demande personnellement et sans engagement.", areas: [{ title: "Bien en Allemagne", desc: "Vous souhaitez vendre directement ou traversez une situation particulière ? Nous examinons votre bien avec discrétion.", cta: "Proposer un bien en Allemagne" }, { title: "Bien en Turquie", desc: "Vous vivez en Allemagne ou en Europe et souhaitez vendre un bien en Turquie ? Adressez-vous d’abord à nous en Allemagne.", cta: "Proposer un bien en Turquie" }] }, ownerInTrouble: { heroTitle: "Des solutions directes pour les biens et terrains.", heroDescription: "De la vente directe à la vacance, la rénovation ou une situation complexe : nous examinons les biens en Allemagne avec discrétion." }, howItWorks: { segmentsTitle: "Nos trois domaines d’activité", segments: [{ title: "Achat immobilier direct", desc: "Biens et terrains en Allemagne, y compris dans des situations complexes ou urgentes." }, { title: "Biens en Turquie", desc: "Examen, achat éventuel ou gestion structurée pour les propriétaires en Europe." }, { title: "Vente et coopérations", desc: "Vente de biens du portefeuille et coopération avec investisseurs, promoteurs et partenaires." }] }, partners: { heroTitle: "Coopérations en Allemagne et en Turquie.", heroDescription: "Nous coopérons avec des promoteurs, sociétés immobilières, investisseurs, agents, partenaires locaux, conseillers et avocats." }, aboutV2: { approach: { headline: "Relier l’Allemagne et la Turquie", body: ["Pour les biens en Turquie, nous nous appuyons sur des partenaires locaux, des conseillers et des avocats.", "Les propriétaires peuvent commencer leur démarche depuis l’Allemagne ou un autre pays européen.", "Aurelia ne fournit pas de conseil juridique ou fiscal ; des experts externes sont associés si nécessaire."] }, situations: { headline: "Marchés et activités", items: ["Achat immobilier en Allemagne", "Biens en Turquie pour les propriétaires résidant en Allemagne ou en Europe", "Vente de biens sélectionnés du portefeuille propre", "Coopérations par projet en Allemagne et en Turquie", "Évaluation directe, discrète et structurée", "Partenaires locaux et conseillers lorsque nécessaire"] } } },
};
