import type { Language, Translations } from "./types";
type DeepPartial<T> = { [K in keyof T]?: T[K] extends Array<infer U> ? U[] : T[K] extends object ? DeepPartial<T[K]> : T[K] };
const data = {
 de: { owner: ["Immobilie in der Türkei?", "Sie leben in Deutschland oder Europa und möchten eine Immobilie in der Türkei verkaufen?", "Zum Türkei-Bereich"], turkey: ["Immobilie in Deutschland?", "Auch Immobilien und Grundstücke in Deutschland prüfen wir direkt und auf eigene Rechnung.", "Zum Bereich Eigentümer"], fields: ["Aktueller Aufenthaltsort des Eigentümers", "Anzahl der Eigentümer"], location: ["Meine Immobilie befindet sich in", "Deutschland", "Türkei", "Für Immobilien in der Türkei nutzen Sie bitte unser ausführliches Formular.", "Zum Türkei-Formular"] },
 en: { owner: ["Property in Turkey?", "Do you live in Germany or Europe and want to sell property in Turkey?", "Go to Turkey section"], turkey: ["Property in Germany?", "We also review property and land in Germany directly and for our own account.", "Go to owner section"], fields: ["Owner's current place of residence", "Number of owners"], location: ["My property is located in", "Germany", "Turkey", "For property in Turkey, please use our detailed form.", "Go to Turkey form"] },
 tr: { owner: ["Türkiye'de gayrimenkulünüz mü var?", "Almanya'da veya Avrupa'da yaşıyor ve Türkiye'deki gayrimenkulünüzü satmak mı istiyorsunuz?", "Türkiye bölümüne git"], turkey: ["Almanya'da gayrimenkulünüz mü var?", "Almanya'daki gayrimenkul ve arsaları da doğrudan ve kendi hesabımıza inceliyoruz.", "Malik bölümüne git"], fields: ["Malikin güncel ikamet yeri", "Malik sayısı"], location: ["Gayrimenkulümün bulunduğu ülke", "Almanya", "Türkiye", "Türkiye'deki gayrimenkuller için ayrıntılı formumuzu kullanın.", "Türkiye formuna git"] },
 nl: { owner: ["Vastgoed in Turkije?", "Woont u in Duitsland of Europa en wilt u vastgoed in Turkije verkopen?", "Naar Turkije"], turkey: ["Vastgoed in Duitsland?", "Ook vastgoed en grond in Duitsland beoordelen wij rechtstreeks en voor eigen rekening.", "Naar eigenaren"], fields: ["Huidige woonplaats van de eigenaar", "Aantal eigenaren"], location: ["Mijn vastgoed bevindt zich in", "Duitsland", "Turkije", "Gebruik voor vastgoed in Turkije ons uitgebreide formulier.", "Naar het Turkije-formulier"] },
 it: { owner: ["Immobile in Turchia?", "Vive in Germania o in Europa e desidera vendere un immobile in Turchia?", "Vai alla sezione Turchia"], turkey: ["Immobile in Germania?", "Valutiamo direttamente e per conto proprio anche immobili e terreni in Germania.", "Vai alla sezione proprietari"], fields: ["Attuale luogo di residenza del proprietario", "Numero di proprietari"], location: ["Il mio immobile si trova in", "Germania", "Turchia", "Per gli immobili in Turchia utilizzi il nostro modulo dettagliato.", "Vai al modulo Turchia"] },
 es: { owner: ["¿Inmueble en Turquía?", "¿Vive en Alemania o Europa y desea vender un inmueble en Turquía?", "Ir a Turquía"], turkey: ["¿Inmueble en Alemania?", "También revisamos directamente y por cuenta propia inmuebles y terrenos en Alemania.", "Ir a propietarios"], fields: ["Lugar de residencia actual del propietario", "Número de propietarios"], location: ["Mi inmueble se encuentra en", "Alemania", "Turquía", "Para inmuebles en Turquía, utilice nuestro formulario detallado.", "Ir al formulario de Turquía"] },
 fr: { owner: ["Un bien en Turquie ?", "Vous vivez en Allemagne ou en Europe et souhaitez vendre un bien en Turquie ?", "Vers la rubrique Turquie"], turkey: ["Un bien en Allemagne ?", "Nous examinons également directement et pour notre propre compte les biens et terrains en Allemagne.", "Vers la rubrique propriétaires"], fields: ["Lieu de résidence actuel du propriétaire", "Nombre de propriétaires"], location: ["Mon bien se trouve en", "Allemagne", "Turquie", "Pour un bien en Turquie, utilisez notre formulaire détaillé.", "Vers le formulaire Turquie"] },
} as const;
export const journeyEnhancements = Object.fromEntries(Object.entries(data).map(([lang, v]) => [lang, {
 ownerInTrouble: { crossLink: { title: v.owner[0], text: v.owner[1], cta: v.owner[2] } },
 turkeyProperties: { crossLink: { title: v.turkey[0], text: v.turkey[1], cta: v.turkey[2] }, form: { ownerLocation: v.fields[0], ownerCount: v.fields[1] } },
 contact: { propertyLocation: v.location[0], propertyLocationOptions: [v.location[1], v.location[2]], turkeyFormHint: v.location[3], turkeyFormCta: v.location[4] },
}])) as Record<Language, DeepPartial<Translations>>;
