import type { Language, Translations } from "./types";
type DeepPartial<T> = { [K in keyof T]?: T[K] extends Array<infer U> ? U[] : T[K] extends object ? DeepPartial<T[K]> : T[K] };
const data = {
  de: { owner: ["Immobilie in der Türkei?", "Sie leben in Deutschland oder Europa und möchten eine Immobilie in der Türkei verkaufen? Dafür haben wir einen eigenen Bereich.", "Zum Türkei-Bereich"], turkey: ["Immobilie in Deutschland?", "Sie möchten eine Immobilie in Deutschland verkaufen? Auch hier prüft Aurelia einen möglichen Ankauf auf eigene Rechnung.", "ZUM BEREICH FÜR EIGENTÜMER"], fields: ["Aktueller Aufenthaltsort des Eigentümers", "Anzahl der Eigentümer"], location: ["Meine Immobilie befindet sich in", "Deutschland", "Türkei", "Für Immobilien in der Türkei nutzen Sie bitte unser ausführliches Formular.", "Zum Türkei-Formular"] },
 en: { owner: ["Property in Turkey?", "Do you live in Germany or Europe and want to sell a property in Turkey? We have a dedicated section for that.", "Go to Turkey section"], turkey: ["Property in Germany?", "Want to sell a property in Germany? You can come to us directly for that too.", "Go to owner section"], fields: ["Owner's current place of residence", "Number of owners"], location: ["My property is located in", "Germany", "Turkey", "For property in Turkey, please use our detailed form.", "Go to Turkey form"] },
 tr: { owner: ["Türkiye'de gayrimenkulünüz mü var?", "Almanya'da veya Avrupa'da yaşıyor ve Türkiye'deki gayrimenkulünüzü satmak mı istiyorsunuz? Bunun için ayrı bir bölümümüz var.", "Türkiye bölümüne git"], turkey: ["Almanya'da gayrimenkulünüz mü var?", "Almanya'da bir gayrimenkul satmak mı istiyorsunuz? Bunun için de doğrudan bize başvurabilirsiniz.", "Malik bölümüne git"], fields: ["Malikin güncel ikamet yeri", "Malik sayısı"], location: ["Gayrimenkulümün bulunduğu ülke", "Almanya", "Türkiye", "Türkiye'deki gayrimenkuller için ayrıntılı formumuzu kullanın.", "Türkiye formuna git"] },
 nl: { owner: ["Vastgoed in Turkije?", "Woont u in Duitsland of Europa en wilt u vastgoed in Turkije verkopen? Daarvoor hebben wij een apart onderdeel.", "Naar Turkije"], turkey: ["Vastgoed in Duitsland?", "Wilt u vastgoed in Duitsland verkopen? Ook daarvoor kunt u rechtstreeks bij ons terecht.", "Naar eigenaren"], fields: ["Huidige woonplaats van de eigenaar", "Aantal eigenaren"], location: ["Mijn vastgoed bevindt zich in", "Duitsland", "Turkije", "Gebruik voor vastgoed in Turkije ons uitgebreide formulier.", "Naar het Turkije-formulier"] },
 it: { owner: ["Immobile in Turchia?", "Vive in Germania o in Europa e desidera vendere un immobile in Turchia? Per questo abbiamo una sezione dedicata.", "Vai alla sezione Turchia"], turkey: ["Immobile in Germania?", "Desidera vendere un immobile in Germania? Anche in questo caso può rivolgersi direttamente a noi.", "Vai alla sezione proprietari"], fields: ["Attuale luogo di residenza del proprietario", "Numero di proprietari"], location: ["Il mio immobile si trova in", "Germania", "Turchia", "Per gli immobili in Turchia utilizzi il nostro modulo dettagliato.", "Vai al modulo Turchia"] },
 es: { owner: ["¿Inmueble en Turquía?", "¿Vive en Alemania o Europa y desea vender un inmueble en Turquía? Para eso contamos con un apartado propio.", "Ir a Turquía"], turkey: ["¿Inmueble en Alemania?", "¿Desea vender un inmueble en Alemania? También en ese caso puede dirigirse directamente a nosotros.", "Ir a propietarios"], fields: ["Lugar de residencia actual del propietario", "Número de propietarios"], location: ["Mi inmueble se encuentra en", "Alemania", "Turquía", "Para inmuebles en Turquía, utilice nuestro formulario detallado.", "Ir al formulario de Turquía"] },
 fr: { owner: ["Un bien en Turquie ?", "Vous vivez en Allemagne ou en Europe et souhaitez vendre un bien en Turquie ? Nous avons une rubrique dédiée à cela.", "Vers la rubrique Turquie"], turkey: ["Un bien en Allemagne ?", "Vous souhaitez vendre un bien en Allemagne ? Vous pouvez aussi vous adresser directement à nous pour cela.", "Vers la rubrique propriétaires"], fields: ["Lieu de résidence actuel du propriétaire", "Nombre de propriétaires"], location: ["Mon bien se trouve en", "Allemagne", "Turquie", "Pour un bien en Turquie, utilisez notre formulaire détaillé.", "Vers le formulaire Turquie"] },
} as const;
export const journeyEnhancements = Object.fromEntries(Object.entries(data).map(([lang, v]) => [lang, {
 ownerInTrouble: { crossLink: { title: v.owner[0], text: v.owner[1], cta: v.owner[2] } },
 turkeyProperties: { crossLink: { title: v.turkey[0], text: v.turkey[1], cta: v.turkey[2] }, form: { ownerLocation: v.fields[0], ownerCount: v.fields[1] } },
 contact: { propertyLocation: v.location[0], propertyLocationOptions: [v.location[1], v.location[2]], turkeyFormHint: v.location[3], turkeyFormCta: v.location[4] },
}])) as Record<Language, DeepPartial<Translations>>;
