import type { Language } from "./types";

type PageExtras = {
  imageCredits: { first: string; second: string; aiDisclosure: string; stockCredit: string; contact: string };
  contact: { availabilityShort: string; personalPrompt: string; consultation: string; consultationSubject: string; phone: string; email: string; confirmationWarning: string };
  portfolio: {
    seoTitle: string; heroKicker: string; heroTitle: string; heroDescription: string; heroAlt: string;
    introTitle: string; introText: string; categoriesTitle: string; categoriesIntro: string;
    categories: { title: string; description: string; alt: string }[];
    regionTitle: string; regionText: string; ctaTitle: string; ctaText: string; ctaButton: string;
  };
  accessibility: { chooseLetters: string; homeHeroAlt: string; promisesAlt: string };
  shared: { faqPrompt: string; call: string; enquire: string; offerProperty: string; faqHeroAlt: string };
};

export const pageExtras: Record<Language, PageExtras> = {
  de: {
    imageCredits: {
      first: "Auf dieser Website werden sowohl KI-generierte Bildmotive als auch lizenzierte Stockfotos verwendet. KI-generierte Darstellungen dienen ausschließlich der Illustration.",
      second: "Nachweise zu verwendeten Stockfotos sind nachfolgend aufgeführt. Sollten dennoch Rechte Dritter betroffen sein, bitten wir um umgehende Kontaktaufnahme.",
      aiDisclosure: "Fotorealistische Bildmotive auf dieser Website wurden teilweise oder vollständig mithilfe generativer künstlicher Intelligenz erstellt oder wesentlich bearbeitet. Sie dienen der Illustration. Soweit nicht ausdrücklich anders angegeben, zeigen diese Darstellungen keine konkreten zum Verkauf stehenden Immobilien, tatsächlichen Geschäftsräume oder realen Standorte der Aurelia Grundbesitz GmbH. Als ‚Symbolbild‘ gekennzeichnete Darstellungen bilden kein konkretes Bestandsobjekt ab.",
      stockCredit: "Startseiten-Hero: Adobe Stock, Datei-Nr. 14562359, Foto: Thorsten Donig. Deutschland-Karte: Pexels, Foto-ID 22081475 (auch in der Länderauswahl des Formulars). Türkei-Karte: Pexels, Foto-ID 39511030 (auch in der Länderauswahl des Formulars). Türkei-Hero: Adobe Stock, Datei-Nr. 502929748. Eigentümer-Hero: Adobe Stock, Datei-Nr. 368296755. Eigentümer-Karten: Pexels, Foto-ID 32992049. Eigentümer-Karte „Komplexe oder zeitkritische Situation“: Adobe Stock, Datei-Nr. 536875854. Eigentümer-Karte „Direkter Verkaufswunsch“: Pexels, Foto-ID 8439664, Foto: Kampus Production. Eigentümer-Karte „Mehrere Eigentümer oder Erbfall“: Pexels, Foto-ID 8204941. Käufer-Hero: Adobe Stock, Datei-Nr. 302581671. Käufer-Karte „Ansprechpartner“: Adobe Stock, Datei-Nr. 356467514. Käufer-Karte „Kaufabwicklung“: Adobe Stock, Datei-Nr. 586889892.",
      contact: "Kontakt bei Rückfragen",
    },
    contact: {
      availabilityShort: "Mo–Fr, auch kurzfristig bei laufenden Verfahren",
      personalPrompt: "Sie möchten persönlich mit uns sprechen? Vereinbaren Sie gerne einen Termin.",
      consultation: "Kostenloses Erstgespräch",
      consultationSubject: "Kostenloses Erstgespräch anfordern",
      phone: "Telefon",
      email: "E-Mail",
      confirmationWarning: "Ihre Anfrage ist eingegangen. Die automatische E-Mail-Bestätigung konnte derzeit nicht zugestellt werden.",
    },
    portfolio: {
      seoTitle: "Portfolio – Aurelia Grundbesitz GmbH", heroKicker: "Portfolio", heroTitle: "Immobilien aus unserem Bestand", heroDescription: "Welche Immobilien aktuell verfügbar sind, erfahren Sie direkt bei uns.", heroAlt: "Aurelia Immobilien-Portfolio",
      introTitle: "Unser Bestand verändert sich", introText: "Immobilien werden gekauft und wieder verkauft. Deshalb verändert sich auch unser Bestand. Nicht jedes Objekt wird öffentlich auf unserer Website angeboten. Wenn Sie nach einer bestimmten Immobilie suchen, können Sie uns direkt ansprechen.",
      categoriesTitle: "Objektkategorien", categoriesIntro: "Je nach aktuellem Bestand können unterschiedliche Immobilienarten verfügbar sein.",
      categories: [
        { title: "Eigentumswohnungen", description: "Einzelne Wohnungen und Wohnobjekte unterschiedlicher Größe.", alt: "Modernes Wohngebäude mit Balkonen" },
        { title: "Einfamilienhäuser", description: "Wohnhäuser in unterschiedlichem Zustand und verschiedenen Lagen.", alt: "Freistehendes Einfamilienhaus" },
        { title: "Grundstücke", description: "Grundstücke und Flächen mit unterschiedlichen Nutzungsmöglichkeiten.", alt: "Luftbild eines Baugrundstücks" },
        { title: "Gewerbeimmobilien", description: "Gewerblich genutzte Immobilien und Objekte mit gemischter Nutzung.", alt: "Außenansicht eines Bürogebäudes" },
      ],
      regionTitle: "Unsere Märkte", regionText: "Unser Schwerpunkt liegt in Deutschland. Darüber hinaus beschäftigen wir uns mit Immobilien in der Türkei und arbeiten bei passenden Projekten mit ausgewählten Geschäftspartnern zusammen.",
      ctaTitle: "Sie suchen eine Immobilie?", ctaText: "Sagen Sie uns kurz, wonach Sie suchen. Wir prüfen, ob sich aktuell ein passendes Objekt in unserem Bestand befindet oder angeboten werden kann.", ctaButton: "Portfolio anfragen",
    },
    accessibility: { chooseLetters: "Buchstaben wählen", homeHeroAlt: "Ruhige Wohnstraße mit gepflegtem Mehrfamilienhaus bei Tageslicht", promisesAlt: "Vier Marmorsäulen in einem lichtdurchfluteten Raum als Sinnbild für unsere vier Versprechen" },
    shared: { faqPrompt: "Weitere Fragen beantworten wir in unseren FAQ.", call: "Anrufen", enquire: "Anfragen", offerProperty: "Immobilie anbieten", faqHeroAlt: "Ruhiger Besprechungsraum mit Immobilienunterlagen" },
  },
  tr: {
    imageCredits: {
      first: "Bu internet sitesinde hem yapay zekâ ile oluşturulan görseller hem de lisanslı stok fotoğraflar kullanılmaktadır. Yapay zekâ ile oluşturulan görseller yalnızca görsel anlatım amacı taşır.",
      second: "Kullanılan stok fotoğraflara ilişkin bilgiler aşağıda yer almaktadır. Buna rağmen üçüncü kişilere ait hakların etkilenmiş olabileceğini düşünüyorsanız, lütfen derhal bizimle iletişime geçin.",
      aiDisclosure: "Bu internet sitesindeki fotogerçekçi görseller kısmen veya tamamen üretken yapay zekâ yardımıyla oluşturulmuş ya da önemli ölçüde düzenlenmiştir. Yalnızca görsel anlatım amacı taşırlar. Açıkça aksi belirtilmedikçe bu görseller, satışa sunulan belirli gayrimenkulleri, Aurelia Grundbesitz GmbH'nin gerçek iş yerlerini veya gerçek konumlarını göstermez. ‘Temsili’ olarak işaretlenen görseller belirli bir portföy gayrimenkulünü yansıtmaz.",
      stockCredit: "Ana sayfa hero görseli: Adobe Stock, dosya no. 14562359, fotoğraf: Thorsten Donig. Almanya kartı: Pexels, fotoğraf kimliği 22081475 (form ülke seçiminde de). Türkiye kartı: Pexels, fotoğraf kimliği 39511030 (form ülke seçiminde de). Türkiye hero görseli: Adobe Stock, dosya no. 502929748. Ev sahibi hero görseli: Adobe Stock, dosya no. 368296755. Ev sahibi kartları: Pexels, fotoğraf kimliği 32992049. Ev sahibi kartı „Karmaşık veya zaman açısından kritik durum“: Adobe Stock, dosya no. 536875854. Ev sahibi kartı „Doğrudan satış isteği“: Pexels, fotoğraf kimliği 8439664, fotoğraf: Kampus Production. Ev sahibi kartı „Birden fazla malik veya miras“: Pexels, fotoğraf kimliği 8204941. Alıcı hero görseli: Adobe Stock, dosya no. 302581671. Alıcı kartı „Muhatabınız“: Adobe Stock, dosya no. 356467514. Alıcı kartı „Satın alma işlemi“: Adobe Stock, dosya no. 586889892.",
      contact: "Sorularınız için iletişim",
    },
    contact: { availabilityShort: "Pazartesi–Cuma; devam eden işlemlerde kısa sürede de ulaşabilirsiniz", personalPrompt: "Bizimle yüz yüze görüşmek mi istersiniz? Dilerseniz bir randevu ayarlayalım.", consultation: "Ücretsiz ilk görüşme", consultationSubject: "Ücretsiz ilk görüşme talebi", phone: "Telefon", email: "E-posta", confirmationWarning: "Talebiniz bize ulaştı. Otomatik e-posta onayı şu anda teslim edilemedi." },
    portfolio: {
      seoTitle: "Portföy – Aurelia Grundbesitz GmbH", heroKicker: "Portföy", heroTitle: "Portföyümüzdeki gayrimenkuller", heroDescription: "Şu anda hangi gayrimenkullerin uygun olduğunu doğrudan bizden öğrenebilirsiniz.", heroAlt: "Aurelia gayrimenkul portföyü",
      introTitle: "Portföyümüz sürekli değişiyor", introText: "Gayrimenkuller alınıp tekrar satıldığı için portföyümüz de sürekli değişir. Her gayrimenkul internet sitemizde herkese açık olarak sunulmaz. Belirli bir gayrimenkul arıyorsanız doğrudan bizimle iletişime geçebilirsiniz.",
      categoriesTitle: "Gayrimenkul kategorileri", categoriesIntro: "Güncel portföyümüze bağlı olarak farklı gayrimenkul türleri mevcut olabilir.",
      categories: [
        { title: "Kat mülkiyetli daireler", description: "Farklı büyüklüklerde bağımsız daireler ve konut birimleri.", alt: "Balkonlu modern konut binası" },
        { title: "Müstakil evler", description: "Farklı durumlarda ve konumlarda müstakil evler.", alt: "Müstakil ev" },
        { title: "Arsalar", description: "Farklı kullanım imkânları sunan arsa ve arazi parçaları.", alt: "Bir arsanın havadan görünümü" },
        { title: "Ticari gayrimenkuller", description: "Ticari amaçla kullanılan gayrimenkuller ve karma kullanımlı yapılar.", alt: "Bir ofis binasının dış görünümü" },
      ],
      regionTitle: "Pazarlarımız", regionText: "Odak noktamız Almanya'dır. Bunun yanı sıra Türkiye'deki gayrimenkullerle de ilgileniyor ve uygun projelerde seçili iş ortaklarımızla çalışıyoruz.",
      ctaTitle: "Bir gayrimenkul mü arıyorsunuz?", ctaText: "Aradığınız gayrimenkulü kısaca bize anlatın. Portföyümüzde şu anda uygun bir gayrimenkul olup olmadığını ya da sunulup sunulamayacağını kontrol edelim.", ctaButton: "Portföy hakkında bilgi alın",
    },
    accessibility: { chooseLetters: "Harf seçin", homeHeroAlt: "Gün ışığında, sakin bir sokakta bakımlı apartman", promisesAlt: "Dört taahhüdümüzü simgeleyen, aydınlık bir mekândaki dört mermer sütun" },
    shared: { faqPrompt: "Diğer sorularınızı SSS bölümümüzde yanıtlıyoruz.", call: "Arayın", enquire: "Talep gönderin", offerProperty: "Gayrimenkul sunun", faqHeroAlt: "Gayrimenkul belgelerinin bulunduğu sakin bir toplantı odası" },
  },
  en: {
    imageCredits: { first: "This website uses both AI-generated imagery and licensed stock photography. AI-generated imagery is used solely for illustrative purposes.", second: "Credits for the stock photography used are listed below. If you nevertheless believe that third-party rights may be affected, please contact us immediately.", aiDisclosure: "Photorealistic imagery on this website was created in part or in full using generative artificial intelligence, or was substantially edited with it. It is provided for illustrative purposes. Unless expressly stated otherwise, these images do not show specific properties for sale, actual business premises or real locations of Aurelia Grundbesitz GmbH. Images marked ‘Illustrative’ do not depict a specific property from our portfolio.", stockCredit: "Homepage hero: Adobe Stock, file no. 14562359, photo: Thorsten Donig. Germany card: Pexels, photo ID 22081475 (also in the form's country selection). Turkey card: Pexels, photo ID 39511030 (also in the form's country selection). Turkey hero: Adobe Stock, file no. 502929748. Owner hero: Adobe Stock, file no. 368296755. Owner cards: Pexels, photo ID 32992049. Owner card 'Complex or time-sensitive situation': Adobe Stock, file no. 536875854. Owner card 'Direct wish to sell': Pexels, photo ID 8439664, photo: Kampus Production. Owner card 'Several owners or inheritance': Pexels, photo ID 8204941. Buyer hero: Adobe Stock, file no. 302581671. Buyer card 'Point of contact': Adobe Stock, file no. 356467514. Buyer card 'Purchase process': Adobe Stock, file no. 586889892.", contact: "Contact for enquiries" },
    contact: { availabilityShort: "Monday–Friday, including at short notice during ongoing proceedings", personalPrompt: "Would you rather speak to us in person? Feel free to arrange an appointment.", consultation: "Free initial consultation", consultationSubject: "Request a free initial consultation", phone: "Phone", email: "Email", confirmationWarning: "Your enquiry has been received. The automatic email confirmation could not be delivered at this time." },
    portfolio: {
      seoTitle: "Portfolio – Aurelia Grundbesitz GmbH", heroKicker: "Portfolio", heroTitle: "Properties from our portfolio", heroDescription: "To find out which properties are currently available, please get in touch with us directly.", heroAlt: "Aurelia property portfolio",
      introTitle: "Our portfolio keeps changing", introText: "Properties are bought and sold again, which is why our portfolio is constantly changing. Not every property is listed publicly on our website. If you are looking for a particular property, feel free to contact us directly.", categoriesTitle: "Property categories", categoriesIntro: "Depending on our current portfolio, different types of properties may be available.",
      categories: [{ title: "Condominiums", description: "Individual flats and residential units of various sizes.", alt: "Modern residential building with balconies" }, { title: "Detached houses", description: "Homes in various conditions and locations.", alt: "Detached family home" }, { title: "Land", description: "Plots and land with various possible uses.", alt: "Aerial view of a building plot" }, { title: "Commercial properties", description: "Commercially used properties and mixed-use buildings.", alt: "Exterior view of an office building" }],
      regionTitle: "Our markets", regionText: "Our focus is on Germany. In addition, we deal with properties in Turkey and work with selected business partners on suitable projects.", ctaTitle: "Looking for a property?", ctaText: "Briefly tell us what you are looking for. We will check whether a suitable property is currently available in our portfolio or can be offered.", ctaButton: "Enquire about our portfolio",
    },
    accessibility: { chooseLetters: "Choose a letter", homeHeroAlt: "Well-maintained apartment building on a quiet residential street in daylight", promisesAlt: "Four marble columns in a light-filled room symbolising our four commitments" },
    shared: { faqPrompt: "We answer further questions in our FAQ.", call: "Call", enquire: "Enquire", offerProperty: "Submit a property", faqHeroAlt: "Calm meeting room with property documents" },
  },
  nl: {
    imageCredits: { first: "Op deze website worden zowel met AI gegenereerde beelden als gelicentieerde stockfoto's gebruikt. Met AI gegenereerde beelden dienen uitsluitend ter illustratie.", second: "De bronvermeldingen van de gebruikte stockfoto's staan hieronder. Denkt u desondanks dat rechten van derden mogelijk zijn geraakt, neem dan onmiddellijk contact met ons op.", aiDisclosure: "Fotorealistische beeldmotieven op deze website zijn gedeeltelijk of volledig met generatieve kunstmatige intelligentie gemaakt of daarmee ingrijpend bewerkt. Ze dienen ter illustratie. Tenzij uitdrukkelijk anders vermeld, tonen deze beelden geen concrete te koop aangeboden objecten, daadwerkelijke bedrijfsruimten of echte vestigingslocaties van Aurelia Grundbesitz GmbH. Als ‘Illustratief’ aangeduide beelden tonen geen concreet object uit de portefeuille.", stockCredit: "Hero op de homepage: Adobe Stock, bestand nr. 14562359, foto: Thorsten Donig. Duitsland-kaart: Pexels, foto-ID 22081475 (ook bij de landkeuze in het formulier). Turkije-kaart: Pexels, foto-ID 39511030 (ook bij de landkeuze in het formulier). Turkije-hero: Adobe Stock, bestand nr. 502929748. Hero voor eigenaren: Adobe Stock, bestand nr. 368296755. Kaarten voor eigenaren: Pexels, foto-ID 32992049. Eigenaarskaart 'Complexe of tijdkritische situatie': Adobe Stock, bestand nr. 536875854. Eigenaarskaart 'Directe verkoopwens': Pexels, foto-ID 8439664, foto: Kampus Production. Eigenaarskaart 'Meerdere eigenaren of erfenis': Pexels, foto-ID 8204941. Kopershero: Adobe Stock, bestand nr. 302581671. Koperskaart 'Aanspreekpunt': Adobe Stock, bestand nr. 356467514. Koperskaart 'Koopafwikkeling': Adobe Stock, bestand nr. 586889892.", contact: "Contact bij vragen" },
    contact: { availabilityShort: "Maandag–vrijdag, ook op korte termijn bij lopende procedures", personalPrompt: "Wilt u liever persoonlijk met ons spreken? Maak gerust een afspraak.", consultation: "Gratis eerste gesprek", consultationSubject: "Gratis eerste gesprek aanvragen", phone: "Telefoon", email: "E-mail", confirmationWarning: "Uw aanvraag is ontvangen. De automatische e-mailbevestiging kon momenteel niet worden bezorgd." },
    portfolio: {
      seoTitle: "Portefeuille – Aurelia Grundbesitz GmbH", heroKicker: "Portefeuille", heroTitle: "Vastgoed uit onze portefeuille", heroDescription: "Welk vastgoed op dit moment beschikbaar is, verneemt u rechtstreeks van ons.", heroAlt: "Vastgoedportefeuille van Aurelia",
      introTitle: "Onze portefeuille verandert voortdurend", introText: "Vastgoed wordt aangekocht en weer verkocht. Daardoor verandert ook onze portefeuille voortdurend. Niet elk object wordt openbaar op onze website aangeboden. Zoekt u een bepaald object, neem dan gerust rechtstreeks contact met ons op.", categoriesTitle: "Vastgoedcategorieën", categoriesIntro: "Afhankelijk van onze actuele portefeuille kunnen uiteenlopende typen vastgoed beschikbaar zijn.",
      categories: [{ title: "Appartementen", description: "Afzonderlijke woningen en woonobjecten van uiteenlopende grootte.", alt: "Modern woongebouw met balkons" }, { title: "Eengezinswoningen", description: "Woningen in uiteenlopende staat en op verschillende locaties.", alt: "Vrijstaande eengezinswoning" }, { title: "Percelen", description: "Percelen en gronden met uiteenlopende gebruiksmogelijkheden.", alt: "Luchtfoto van een bouwperceel" }, { title: "Commercieel vastgoed", description: "Commercieel gebruikte panden en gebouwen met gemengd gebruik.", alt: "Buitenzijde van een kantoorgebouw" }],
      regionTitle: "Onze markten", regionText: "Onze focus ligt op Duitsland. Daarnaast houden wij ons bezig met vastgoed in Turkije en werken wij bij passende projecten samen met geselecteerde zakenpartners.", ctaTitle: "Op zoek naar vastgoed?", ctaText: "Vertel ons kort waarnaar u op zoek bent. Wij kijken of er momenteel een passend object in onze portefeuille beschikbaar is of aangeboden kan worden.", ctaButton: "Portefeuille aanvragen",
    },
    accessibility: { chooseLetters: "Kies een letter", homeHeroAlt: "Goed onderhouden appartementencomplex in een rustige woonstraat bij daglicht", promisesAlt: "Vier marmeren zuilen in een lichte ruimte als symbool voor onze vier beloften" },
    shared: { faqPrompt: "Meer vragen beantwoorden wij in onze FAQ.", call: "Bellen", enquire: "Aanvragen", offerProperty: "Vastgoed aanbieden", faqHeroAlt: "Rustige vergaderruimte met vastgoeddocumenten" },
  },
  it: {
    imageCredits: { first: "Questo sito utilizza sia immagini generate con l'intelligenza artificiale sia fotografie stock con licenza. Le immagini generate con l'IA sono utilizzate esclusivamente a scopo illustrativo.", second: "I crediti delle fotografie stock utilizzate sono riportati di seguito. Qualora ritenesse comunque che possano essere stati lesi diritti di terzi, la preghiamo di contattarci immediatamente.", aiDisclosure: "Le immagini fotorealistiche presenti su questo sito sono state create in tutto o in parte con l'ausilio dell'intelligenza artificiale generativa oppure sono state sostanzialmente modificate con essa. Hanno scopo illustrativo. Salvo diversa indicazione esplicita, non raffigurano immobili specifici in vendita, sedi operative effettive o luoghi reali di Aurelia Grundbesitz GmbH. Le immagini contrassegnate come ‘Illustrativa’ non rappresentano un immobile specifico del portafoglio.", stockCredit: "Hero della homepage: Adobe Stock, file n. 14562359, foto: Thorsten Donig. Scheda Germania: Pexels, foto ID 22081475 (anche nella scelta del paese del modulo). Scheda Turchia: Pexels, foto ID 39511030 (anche nella scelta del paese del modulo). Hero Turchia: Adobe Stock, file n. 502929748. Hero proprietari: Adobe Stock, file n. 368296755. Schede proprietari: Pexels, foto ID 32992049. Scheda proprietari 'Situazione complessa o urgente': Adobe Stock, file n. 536875854. Scheda proprietari 'Vendita diretta': Pexels, foto ID 8439664, foto: Kampus Production. Scheda proprietari 'Più proprietari o eredità': Pexels, foto ID 8204941. Hero acquirenti: Adobe Stock, file n. 302581671. Scheda acquirenti 'Referente': Adobe Stock, file n. 356467514. Scheda acquirenti 'Svolgimento dell'acquisto': Adobe Stock, file n. 586889892.", contact: "Contatti per informazioni" },
    contact: { availabilityShort: "Dal lunedì al venerdì, anche con breve preavviso per procedure in corso", personalPrompt: "Preferisce parlare con noi di persona? Fissi pure un appuntamento.", consultation: "Primo colloquio gratuito", consultationSubject: "Richiesta di primo colloquio gratuito", phone: "Telefono", email: "E-mail", confirmationWarning: "La sua richiesta è stata ricevuta. Al momento non è stato possibile recapitare la conferma automatica via e-mail." },
    portfolio: {
      seoTitle: "Portafoglio – Aurelia Grundbesitz GmbH", heroKicker: "Portafoglio", heroTitle: "Immobili del nostro patrimonio", heroDescription: "Per sapere quali immobili sono attualmente disponibili, ci contatti direttamente.", heroAlt: "Portafoglio immobiliare Aurelia",
      introTitle: "Il nostro patrimonio è in continua evoluzione", introText: "Gli immobili vengono acquistati e rivenduti, per cui anche il nostro patrimonio cambia costantemente. Non tutti gli immobili vengono pubblicati sul nostro sito. Se sta cercando un immobile specifico, può contattarci direttamente.", categoriesTitle: "Categorie di immobili", categoriesIntro: "A seconda del patrimonio attuale, possono essere disponibili diverse tipologie di immobili.",
      categories: [{ title: "Appartamenti di proprietà", description: "Singole unità abitative e immobili residenziali di varie dimensioni.", alt: "Edificio residenziale moderno con balconi" }, { title: "Case unifamiliari", description: "Abitazioni in diverse condizioni e posizioni.", alt: "Casa unifamiliare indipendente" }, { title: "Terreni", description: "Terreni ed aree con diverse possibilità di utilizzo.", alt: "Veduta aerea di un terreno edificabile" }, { title: "Immobili commerciali", description: "Immobili a uso commerciale e edifici a uso misto.", alt: "Vista esterna di un edificio per uffici" }],
      regionTitle: "I nostri mercati", regionText: "Il nostro focus è la Germania. Ci occupiamo inoltre di immobili in Turchia e collaboriamo con partner commerciali selezionati per progetti idonei.", ctaTitle: "Sta cercando un immobile?", ctaText: "Ci dica brevemente cosa sta cercando. Verificheremo se nel nostro patrimonio è attualmente disponibile un immobile adatto o se può esserle proposto.", ctaButton: "Richiedi il portafoglio",
    },
    accessibility: { chooseLetters: "Scegli una lettera", homeHeroAlt: "Edificio residenziale ben tenuto in una tranquilla strada di giorno", promisesAlt: "Quattro colonne di marmo in un ambiente luminoso, simbolo dei nostri quattro impegni" },
    shared: { faqPrompt: "Rispondiamo ad altre domande nelle nostre FAQ.", call: "Chiama", enquire: "Invia richiesta", offerProperty: "Proponi un immobile", faqHeroAlt: "Sala riunioni tranquilla con documenti immobiliari" },
  },
  es: {
    imageCredits: { first: "Este sitio web utiliza tanto imágenes generadas con inteligencia artificial como fotografías de stock con licencia. Las imágenes generadas con IA se utilizan únicamente con fines ilustrativos.", second: "Los créditos de las fotografías de stock utilizadas figuran a continuación. Si, pese a ello, considera que podrían verse afectados derechos de terceros, le rogamos que se ponga en contacto con nosotros de inmediato.", aiDisclosure: "Los motivos fotorealistas de este sitio web se han creado parcial o totalmente mediante inteligencia artificial generativa, o se han modificado de forma sustancial con ella. Se utilizan con fines ilustrativos. Salvo indicación expresa en contrario, estas representaciones no muestran inmuebles concretos en venta, oficinas reales ni ubicaciones reales de Aurelia Grundbesitz GmbH. Las imágenes marcadas como ‘Ilustrativa’ no representan un inmueble concreto de la cartera.", stockCredit: "Hero de la página de inicio: Adobe Stock, archivo n.º 14562359, foto: Thorsten Donig. Tarjeta de Alemania: Pexels, foto ID 22081475 (también en la selección de país del formulario). Tarjeta de Turquía: Pexels, foto ID 39511030 (también en la selección de país del formulario). Hero de Turquía: Adobe Stock, archivo n.º 502929748. Hero de propietarios: Adobe Stock, archivo n.º 368296755. Tarjetas de propietarios: Pexels, foto ID 32992049. Tarjeta de propietarios 'Situación compleja o urgente': Adobe Stock, archivo n.º 536875854. Tarjeta de propietarios 'Deseo de venta directa': Pexels, foto ID 8439664, foto: Kampus Production. Tarjeta de propietarios 'Varios propietarios o herencia': Pexels, foto ID 8204941. Hero de compradores: Adobe Stock, archivo n.º 302581671. Tarjeta de compradores 'Interlocutor': Adobe Stock, archivo n.º 356467514. Tarjeta de compradores 'Tramitación de la compra': Adobe Stock, archivo n.º 586889892.", contact: "Contacto para consultas" },
    contact: { availabilityShort: "De lunes a viernes, también con poca antelación en procedimientos en curso", personalPrompt: "¿Prefiere hablar con nosotros en persona? Concierte una cita cuando lo desee.", consultation: "Primera consulta gratuita", consultationSubject: "Solicitar una primera consulta gratuita", phone: "Teléfono", email: "Correo electrónico", confirmationWarning: "Hemos recibido su consulta. En este momento no ha sido posible entregar la confirmación automática por correo electrónico." },
    portfolio: {
      seoTitle: "Cartera – Aurelia Grundbesitz GmbH", heroKicker: "Cartera", heroTitle: "Inmuebles de nuestra cartera", heroDescription: "Para saber qué inmuebles están disponibles en cada momento, póngase en contacto con nosotros directamente.", heroAlt: "Cartera inmobiliaria de Aurelia",
      introTitle: "Nuestra cartera cambia constantemente", introText: "Los inmuebles se compran y se vuelven a vender, por lo que nuestra cartera también cambia continuamente. No todos los inmuebles se publican en nuestra web. Si busca un inmueble concreto, puede contactarnos directamente.", categoriesTitle: "Categorías de inmuebles", categoriesIntro: "Según la cartera actual, pueden estar disponibles distintos tipos de inmuebles.",
      categories: [{ title: "Viviendas en propiedad", description: "Viviendas individuales y unidades residenciales de distintos tamaños.", alt: "Edificio residencial moderno con balcones" }, { title: "Viviendas unifamiliares", description: "Viviendas en distintos estados y ubicaciones.", alt: "Vivienda unifamiliar independiente" }, { title: "Terrenos", description: "Terrenos y superficies con distintas posibilidades de uso.", alt: "Vista aérea de un solar" }, { title: "Inmuebles comerciales", description: "Inmuebles de uso comercial y edificios de uso mixto.", alt: "Vista exterior de un edificio de oficinas" }],
      regionTitle: "Nuestros mercados", regionText: "Nuestro foco está en Alemania. Además, nos ocupamos de inmuebles en Turquía y colaboramos con socios comerciales seleccionados en proyectos adecuados.", ctaTitle: "¿Busca un inmueble?", ctaText: "Cuéntenos brevemente qué busca. Comprobaremos si actualmente hay un inmueble adecuado en nuestra cartera o si puede ofrecérsele uno.", ctaButton: "Consultar la cartera",
    },
    accessibility: { chooseLetters: "Elegir una letra", homeHeroAlt: "Edificio residencial bien cuidado en una calle tranquila a la luz del día", promisesAlt: "Cuatro columnas de mármol en un espacio luminoso como símbolo de nuestros cuatro compromisos" },
    shared: { faqPrompt: "Respondemos a otras preguntas en nuestras FAQ.", call: "Llamar", enquire: "Consultar", offerProperty: "Ofrecer un inmueble", faqHeroAlt: "Sala de reuniones tranquila con documentación inmobiliaria" },
  },
  fr: {
    imageCredits: {
      first: "Ce site utilise à la fois des visuels générés par intelligence artificielle et des photographies de stock sous licence. Les visuels générés par IA servent uniquement à des fins d'illustration.",
      second: "Les crédits des photographies de stock utilisées figurent ci-dessous. Si vous estimez néanmoins que des droits de tiers pourraient être concernés, nous vous prions de bien vouloir nous contacter immédiatement.",
      aiDisclosure: "Les visuels photoréalistes de ce site ont été créés en partie ou intégralement à l'aide d'une intelligence artificielle générative, ou ont été substantiellement retravaillés avec celle-ci. Ils servent à l'illustration. Sauf indication expresse contraire, ces représentations ne montrent aucun bien précis proposé à la vente, aucun local professionnel réel ni aucun site réel d'Aurelia Grundbesitz GmbH. Les visuels portant la mention « Illustratif » ne représentent aucun bien concret du portefeuille.",
      stockCredit: "Hero de la page d’accueil : Adobe Stock, fichier n° 14562359, photo : Thorsten Donig. Carte Allemagne : Pexels, photo ID 22081475 (également dans le choix du pays du formulaire). Carte Turquie : Pexels, photo ID 39511030 (également dans le choix du pays du formulaire). Hero Turquie : Adobe Stock, fichier n° 502929748. Héro propriétaires : Adobe Stock, fichier n° 368296755. Cartes propriétaires : Pexels, photo ID 32992049. Carte propriétaires « Situation complexe ou urgente » : Adobe Stock, fichier n° 536875854. Carte propriétaires « Souhait de vente directe » : Pexels, photo ID 8439664, photo : Kampus Production. Carte propriétaires « Plusieurs propriétaires ou succession » : Pexels, photo ID 8204941. Hero acheteurs : Adobe Stock, fichier n° 302581671. Carte acheteurs « Interlocuteur » : Adobe Stock, fichier n° 356467514. Carte acheteurs « Déroulement de l'achat » : Adobe Stock, fichier n° 586889892.",
      contact: "Contact pour toute question",
    },
    contact: {
      availabilityShort: "Du lundi au vendredi, y compris à court terme en cas de procédure en cours",
      personalPrompt: "Vous préférez nous parler en personne ? N'hésitez pas à convenir d'un rendez-vous.",
      consultation: "Premier entretien gratuit",
      consultationSubject: "Demander un premier entretien gratuit",
      phone: "Téléphone",
      email: "E-mail",
      confirmationWarning: "Votre demande a bien été reçue. La confirmation automatique par e-mail n'a pas pu être délivrée pour le moment.",
    },
    portfolio: {
      seoTitle: "Portefeuille – Aurelia Grundbesitz GmbH", heroKicker: "Portefeuille", heroTitle: "Biens de notre portefeuille", heroDescription: "Pour savoir quels biens sont actuellement disponibles, contactez-nous directement.", heroAlt: "Portefeuille immobilier Aurelia",
      introTitle: "Notre portefeuille évolue constamment", introText: "Des biens sont achetés puis revendus, si bien que notre portefeuille change en permanence. Tous les biens ne sont pas proposés publiquement sur notre site. Si vous recherchez un bien précis, n'hésitez pas à nous contacter directement.",
      categoriesTitle: "Catégories de biens", categoriesIntro: "Selon notre portefeuille actuel, différents types de biens peuvent être disponibles.",
      categories: [
        { title: "Appartements en copropriété", description: "Logements individuels et biens résidentiels de tailles diverses.", alt: "Immeuble résidentiel moderne avec balcons" },
        { title: "Maisons individuelles", description: "Maisons dans différents états et emplacements.", alt: "Maison individuelle indépendante" },
        { title: "Terrains", description: "Terrains et surfaces offrant diverses possibilités d'utilisation.", alt: "Vue aérienne d'un terrain constructible" },
        { title: "Immobilier commercial", description: "Biens à usage commercial et immeubles à usage mixte.", alt: "Vue extérieure d'un immeuble de bureaux" },
      ],
      regionTitle: "Nos marchés", regionText: "Notre priorité est l'Allemagne. Nous nous intéressons également aux biens en Turquie et collaborons avec des partenaires commerciaux sélectionnés sur des projets adaptés.",
      ctaTitle: "Vous cherchez un bien ?", ctaText: "Dites-nous brièvement ce que vous recherchez. Nous vérifierons si un bien adapté est actuellement disponible dans notre portefeuille ou peut être proposé.", ctaButton: "Demander le portefeuille",
    },
    accessibility: { chooseLetters: "Choisir une lettre", homeHeroAlt: "Rue résidentielle calme avec un immeuble bien entretenu en plein jour", promisesAlt: "Quatre colonnes de marbre dans une pièce baignée de lumière, symbole de nos quatre engagements" },
    shared: { faqPrompt: "Nous répondons à vos autres questions dans notre FAQ.", call: "Appeler", enquire: "Faire une demande", offerProperty: "Proposer un bien", faqHeroAlt: "Salle de réunion calme avec des documents immobiliers" },
  },
};

export const taxExternalLinkLabels: Record<Language, {
  afa: [string, string];
  energy: [string, string];
  kfw: [string, string];
  bafa: [string, string];
}> = {
  de: { afa: ["Bundesfinanzministerium", "Finanzamt (ELSTER)"], energy: ["Bundesfinanzministerium", "Bundesministerium – Energieeffizienz"], kfw: ["KfW Förderbank", "KfW Produktfinder"], bafa: ["BAFA", "BAFA Förderübersicht"] },
  en: { afa: ["Federal Ministry of Finance", "Tax authority (ELSTER)"], energy: ["Federal Ministry of Finance", "Federal Ministry – Energy efficiency"], kfw: ["KfW development bank", "KfW product finder"], bafa: ["BAFA", "BAFA funding overview"] },
  nl: { afa: ["Federaal ministerie van Financiën", "Belastingdienst (ELSTER)"], energy: ["Federaal ministerie van Financiën", "Federaal ministerie – Energie-efficiëntie"], kfw: ["KfW-ontwikkelingsbank", "KfW-productzoeker"], bafa: ["BAFA", "BAFA-subsidieoverzicht"] },
  it: { afa: ["Ministero federale delle Finanze", "Ufficio delle imposte (ELSTER)"], energy: ["Ministero federale delle Finanze", "Ministero federale – Efficienza energetica"], kfw: ["Banca di sviluppo KfW", "Ricerca prodotti KfW"], bafa: ["BAFA", "Panoramica degli incentivi BAFA"] },
  es: { afa: ["Ministerio Federal de Finanzas", "Agencia tributaria (ELSTER)"], energy: ["Ministerio Federal de Finanzas", "Ministerio Federal – Eficiencia energética"], kfw: ["Banco de desarrollo KfW", "Buscador de productos KfW"], bafa: ["BAFA", "Resumen de ayudas BAFA"] },
  tr: { afa: ["Federal Maliye Bakanlığı", "Vergi dairesi (ELSTER)"], energy: ["Federal Maliye Bakanlığı", "Federal Bakanlık – Enerji verimliliği"], kfw: ["KfW kalkınma bankası", "KfW ürün arama"], bafa: ["BAFA", "BAFA teşvik programları"] },
  fr: { afa: ["Ministère fédéral des Finances", "Administration fiscale (ELSTER)"], energy: ["Ministère fédéral des Finances", "Ministère fédéral – Efficacité énergétique"], kfw: ["Banque de développement KfW", "Recherche de produits KfW"], bafa: ["BAFA", "Aperçu des aides BAFA"] },
};