import type { Language } from "./types";

export type PropertyOfferCopy = {
  seoTitle: string; seoDescription: string; kicker: string; title: string; intro: string;
  countryQuestion: string; germany: string; turkey: string; requiredHint: string;
  firstName: string; lastName: string; phone: string; email: string; location: string; street: string;
  propertyType: string; area: string; units: string; rooms: string; yearBuilt: string; rented: string;
  ownerStatus: string; price: string; situation: string; details: string; province: string; district: string;
  tapu: string; ownerCount: string; ownerResidence: string; preferredLanguage: string; yes: string; no: string;
  files: string; uploadHelp: string; privacy: string; submit: string; submitting: string;
  successTitle: string; successText: string; confirmationWarning: string; errorTitle: string; errorText: string;
  requiredError: string; emailError: string; fileError: string;
  propertyTypes: string[]; situations: string[]; ownerStatuses: string[]; languages: string[];
};

const base = {
  propertyTypes: ["Wohnung", "Einfamilienhaus", "Mehrfamilienhaus", "Grundstück", "Gewerbeimmobilie", "Sonstiges"],
  situations: ["Normaler Verkauf", "Erbschaft / Erbengemeinschaft", "Finanzielle Belastung", "Laufende Finanzierung", "Zwangsversteigerung", "Mehrere Eigentümer", "Leerstand", "Sanierungsbedarf", "Schwierige Mietverhältnisse", "Sonstiges"],
  ownerStatuses: ["Alleineigentümer", "Miteigentümer", "Erbe / Erbengemeinschaft", "Bevollmächtigter", "Sonstiges"],
  languages: ["Deutsch", "Türkçe", "English", "Nederlands", "Italiano", "Español", "Français"],
};

export const propertyOfferCopy: Record<Language, PropertyOfferCopy> = {
  de: { ...base, seoTitle:"Immobilie anbieten | Aurelia Grundbesitz", seoDescription:"Bieten Sie Aurelia Grundbesitz Ihre Immobilie in Deutschland oder der Türkei vertraulich und unverbindlich an.", kicker:"Vertrauliche Immobilienanfrage", title:"Immobilie anbieten", intro:"Senden Sie uns unverbindlich die wichtigsten Angaben zu Ihrer Immobilie. Wir prüfen Ihre Anfrage vertraulich und melden uns persönlich bei Ihnen.", countryQuestion:"Wo befindet sich Ihre Immobilie?", germany:"Deutschland", turkey:"Türkei", requiredHint:"Mit * gekennzeichnete Felder sind Pflichtfelder.", firstName:"Vorname", lastName:"Nachname", phone:"Telefonnummer", email:"E-Mail-Adresse", location:"Ort / PLZ der Immobilie", street:"Straße / Lage", propertyType:"Immobilienart", area:"Wohnfläche / Grundstücksfläche", units:"Anzahl Einheiten", rooms:"Zimmer", yearBuilt:"Baujahr", rented:"Vermietet?", ownerStatus:"Eigentümerstatus", price:"Gewünschter Verkaufspreis", situation:"Besondere Situation", details:"Weitere Informationen", province:"Provinz / Stadt", district:"Bezirk / Stadtteil", tapu:"Tapu / Eigentumsnachweis vorhanden?", ownerCount:"Anzahl Eigentümer", ownerResidence:"Aktueller Wohnsitz des Eigentümers", preferredLanguage:"Bevorzugte Sprache", yes:"Ja", no:"Nein", files:"Fotos und Unterlagen", uploadHelp:"PDF, JPG, JPEG oder PNG · maximal 10 MB je Datei · höchstens 10 Dateien", privacy:"Ich habe die Datenschutzerklärung gelesen und stimme der Verarbeitung meiner Angaben zur Bearbeitung dieser Anfrage zu.", submit:"Immobilie unverbindlich anbieten", submitting:"Anfrage wird gesendet …", successTitle:"Anfrage erhalten", successText:"Vielen Dank für Ihre Immobilienanfrage. Wir haben Ihre Angaben erhalten und werden uns nach Prüfung persönlich mit Ihnen in Verbindung setzen.", confirmationWarning:"Ihre Anfrage wurde übermittelt. Die Bestätigungsmail konnte jedoch nicht zugestellt werden.", errorTitle:"Versand nicht möglich", errorText:"Ihre Anfrage konnte nicht versendet werden. Bitte versuchen Sie es erneut oder schreiben Sie an office@aureliaestates.de.", requiredError:"Bitte füllen Sie dieses Pflichtfeld aus.", emailError:"Bitte geben Sie eine gültige E-Mail-Adresse ein.", fileError:"Bitte verwenden Sie nur PDF-, JPG-, JPEG- oder PNG-Dateien bis 10 MB." },
  en: { ...base, seoTitle:"Submit a property | Aurelia Grundbesitz", seoDescription:"Submit your property in Germany or Turkey to Aurelia Grundbesitz confidentially and without obligation.", kicker:"Confidential property enquiry", title:"Submit a property", intro:"Send us the key details of your property without obligation. We will review your enquiry confidentially and contact you personally.", countryQuestion:"Where is your property located?", germany:"Germany", turkey:"Turkey", requiredHint:"Fields marked * are required.", firstName:"First name", lastName:"Last name", phone:"Phone number", email:"Email address", location:"Property town / postcode", street:"Street / location", propertyType:"Property type", area:"Living / plot area", units:"Number of units", rooms:"Rooms", yearBuilt:"Year built", rented:"Let?", ownerStatus:"Ownership status", price:"Desired sale price", situation:"Special situation", details:"Further information", province:"Province / city", district:"District / neighbourhood", tapu:"Tapu / proof of ownership available?", ownerCount:"Number of owners", ownerResidence:"Owner's current residence", preferredLanguage:"Preferred language", yes:"Yes", no:"No", files:"Photos and documents", uploadHelp:"PDF, JPG, JPEG or PNG · max. 10 MB per file · up to 10 files", privacy:"I have read the privacy policy and consent to my data being processed for this enquiry.", submit:"Submit property without obligation", submitting:"Sending enquiry …", successTitle:"Enquiry received", successText:"Thank you for your property enquiry. We have received your details and will contact you personally after reviewing them.", confirmationWarning:"Your enquiry was delivered, but the confirmation email could not be delivered.", errorTitle:"Unable to send", errorText:"Your enquiry could not be sent. Please try again or email office@aureliaestates.de.", requiredError:"Please complete this required field.", emailError:"Please enter a valid email address.", fileError:"Please use only PDF, JPG, JPEG or PNG files up to 10 MB." },
  tr: { ...base, seoTitle:"Gayrimenkul sunun | Aurelia Grundbesitz", seoDescription:"Almanya veya Türkiye'deki gayrimenkulünüzü gizli ve bağlayıcı olmadan sunun.", kicker:"Gizli gayrimenkul talebi", title:"Gayrimenkul sunun", intro:"Gayrimenkulünüzle ilgili en önemli bilgileri bağlayıcı olmadan gönderin. Talebinizi gizlilikle inceleyip sizinle şahsen iletişime geçeceğiz.", countryQuestion:"Gayrimenkulünüz nerede?", germany:"Almanya", turkey:"Türkiye", requiredHint:"* işaretli alanlar zorunludur.", firstName:"Ad", lastName:"Soyad", phone:"Telefon numarası", email:"E-posta adresi", location:"Gayrimenkulün yeri / posta kodu", street:"Sokak / konum", propertyType:"Gayrimenkul türü", area:"Konut / arsa alanı", units:"Birim sayısı", rooms:"Oda sayısı", yearBuilt:"Yapım yılı", rented:"Kirada mı?", ownerStatus:"Mülkiyet durumu", price:"İstenen satış fiyatı", situation:"Özel durum", details:"Ek bilgiler", province:"İl / şehir", district:"İlçe / mahalle", tapu:"Tapu / mülkiyet belgesi mevcut mu?", ownerCount:"Malik sayısı", ownerResidence:"Malikin mevcut ikamet yeri", preferredLanguage:"Tercih edilen dil", yes:"Evet", no:"Hayır", files:"Fotoğraf ve belgeler", uploadHelp:"PDF, JPG, JPEG veya PNG · dosya başına en fazla 10 MB · en fazla 10 dosya", privacy:"Gizlilik politikasını okudum ve bilgilerimin bu talep için işlenmesini kabul ediyorum.", submit:"Bağlayıcı olmadan sunun", submitting:"Talep gönderiliyor …", successTitle:"Talebiniz alındı", successText:"Gayrimenkul talebiniz için teşekkür ederiz. Bilgilerinizi aldık ve incelemenin ardından sizinle şahsen iletişime geçeceğiz.", confirmationWarning:"Talebiniz iletildi ancak onay e-postası teslim edilemedi.", errorTitle:"Gönderilemedi", errorText:"Talebiniz gönderilemedi. Lütfen tekrar deneyin veya office@aureliaestates.de adresine yazın.", requiredError:"Lütfen bu zorunlu alanı doldurun.", emailError:"Lütfen geçerli bir e-posta adresi girin.", fileError:"Yalnızca 10 MB'a kadar PDF, JPG, JPEG veya PNG kullanın." },
  nl: {} as PropertyOfferCopy, it: {} as PropertyOfferCopy, es: {} as PropertyOfferCopy, fr: {} as PropertyOfferCopy,
};

propertyOfferCopy.nl = { ...propertyOfferCopy.en, title:"Vastgoed aanbieden", kicker:"Vertrouwelijke vastgoedaanvraag", intro:"Stuur ons vrijblijvend de belangrijkste gegevens over uw vastgoed. Wij beoordelen uw aanvraag vertrouwelijk en nemen persoonlijk contact met u op.", countryQuestion:"Waar bevindt uw vastgoed zich?", germany:"Duitsland", turkey:"Turkije", firstName:"Voornaam", lastName:"Achternaam", phone:"Telefoonnummer", email:"E-mailadres", province:"Provincie / stad", district:"District / wijk", preferredLanguage:"Voorkeurstaal", submit:"Vastgoed vrijblijvend aanbieden", successText:"Dank u voor uw vastgoedaanvraag. Wij hebben uw gegevens ontvangen en nemen na beoordeling persoonlijk contact met u op." };
propertyOfferCopy.it = { ...propertyOfferCopy.en, title:"Proponi un immobile", kicker:"Richiesta immobiliare riservata", intro:"Inviateci senza impegno i dati principali del vostro immobile. Esamineremo la richiesta con riservatezza e vi contatteremo personalmente.", countryQuestion:"Dove si trova il vostro immobile?", germany:"Germania", turkey:"Turchia", firstName:"Nome", lastName:"Cognome", phone:"Telefono", email:"E-mail", province:"Provincia / città", district:"Distretto / quartiere", preferredLanguage:"Lingua preferita", submit:"Proponi l'immobile senza impegno", successText:"Grazie per la richiesta. Abbiamo ricevuto i dati e vi contatteremo personalmente dopo averli esaminati." };
propertyOfferCopy.es = { ...propertyOfferCopy.en, title:"Ofrecer un inmueble", kicker:"Consulta inmobiliaria confidencial", intro:"Envíenos sin compromiso los datos principales de su inmueble. Revisaremos su consulta confidencialmente y nos pondremos en contacto personalmente.", countryQuestion:"¿Dónde se encuentra su inmueble?", germany:"Alemania", turkey:"Turquía", firstName:"Nombre", lastName:"Apellidos", phone:"Teléfono", email:"Correo electrónico", province:"Provincia / ciudad", district:"Distrito / barrio", preferredLanguage:"Idioma preferido", submit:"Ofrecer inmueble sin compromiso", successText:"Gracias por su consulta inmobiliaria. Hemos recibido sus datos y nos pondremos en contacto personalmente después de revisarlos." };
propertyOfferCopy.fr = { ...propertyOfferCopy.en, title:"Proposer un bien immobilier", kicker:"Demande immobilière confidentielle", intro:"Envoyez-nous sans engagement les principales informations sur votre bien. Nous examinerons votre demande en toute confidentialité et vous contacterons personnellement.", countryQuestion:"Où se trouve votre bien immobilier ?", germany:"Allemagne", turkey:"Turquie", firstName:"Prénom", lastName:"Nom", phone:"Téléphone", email:"Adresse e-mail", province:"Province / ville", district:"District / quartier", preferredLanguage:"Langue préférée", submit:"Proposer le bien sans engagement", successText:"Merci pour votre demande immobilière. Nous avons reçu vos informations et vous contacterons personnellement après examen." };
