import type { Language } from "./types";

export type PropertyOfferCopy = {
  seoTitle: string; seoDescription: string; kicker: string; title: string; intro: string;
  countryQuestion: string; germany: string; turkey: string; requiredHint: string;
  firstName: string; lastName: string; phone: string; email: string; location: string; street: string;
  propertyType: string; area: string; units: string; rooms: string; yearBuilt: string; rented: string;
  ownerStatus: string; price: string; situation: string; details: string; province: string; district: string;
  tapu: string; ownerCount: string; ownerResidence: string; preferredLanguage: string; yes: string; no: string;
  files: string; uploadHelp: string; privacy: string; submit: string; submitting: string;
  successTitle: string; successText: string; confirmationWarning: string; errorTitle: string; errorText: string;
  requiredError: string; emailError: string; fileError: string;
  germanyImageAlt: string; turkeyImageAlt: string;
  propertyTypes: string[]; situations: string[]; ownerStatuses: string[]; languages: string[];
};

const base = {
  propertyTypes: ["Wohnung", "Einfamilienhaus", "Mehrfamilienhaus", "Grundstück", "Gewerbeimmobilie", "Sonstiges"],
  situations: ["Normaler Verkauf", "Erbschaft / Erbengemeinschaft", "Finanzielle Belastung", "Laufende Finanzierung", "Zwangsversteigerung", "Mehrere Eigentümer", "Leerstand", "Sanierungsbedarf", "Schwierige Mietverhältnisse", "Sonstiges"],
  ownerStatuses: ["Alleineigentümer", "Miteigentümer", "Erbe / Erbengemeinschaft", "Bevollmächtigter", "Sonstiges"],
  languages: ["Deutsch", "Türkçe", "English", "Nederlands", "Italiano", "Español", "Français"],
};

export const propertyOfferCopy: Record<Language, PropertyOfferCopy> = {
  de: { ...base, seoTitle:"Immobilie anbieten | Aurelia Grundbesitz", seoDescription:"Bieten Sie Aurelia Grundbesitz Ihre Immobilie in Deutschland oder der Türkei vertraulich und unverbindlich an.", kicker:"Vertrauliche Immobilienanfrage", title:"Immobilie anbieten", intro:"Senden Sie uns unverbindlich die wichtigsten Angaben zu Ihrer Immobilie. Wir prüfen Ihre Anfrage vertraulich und melden uns persönlich bei Ihnen.", countryQuestion:"Wo befindet sich Ihre Immobilie?", germany:"Deutschland", turkey:"Türkei", requiredHint:"Mit * gekennzeichnete Felder sind Pflichtfelder.", firstName:"Vorname", lastName:"Nachname", phone:"Telefonnummer", email:"E-Mail-Adresse", location:"Ort / PLZ der Immobilie", street:"Straße / Lage", propertyType:"Immobilienart", area:"Wohnfläche / Grundstücksfläche", units:"Anzahl Einheiten", rooms:"Zimmer", yearBuilt:"Baujahr", rented:"Vermietet?", ownerStatus:"Eigentümerstatus", price:"Gewünschter Verkaufspreis", situation:"Besondere Situation", details:"Weitere Informationen", province:"Provinz / Stadt", district:"Bezirk / Stadtteil", tapu:"Tapu / Eigentumsnachweis vorhanden?", ownerCount:"Anzahl Eigentümer", ownerResidence:"Aktueller Wohnsitz des Eigentümers", preferredLanguage:"Bevorzugte Sprache", yes:"Ja", no:"Nein", files:"Fotos und Unterlagen", uploadHelp:"PDF, JPG, JPEG oder PNG · maximal 10 MB je Datei · höchstens 10 Dateien", privacy:"Ich habe die Datenschutzerklärung gelesen und stimme der Verarbeitung meiner Angaben zur Bearbeitung dieser Anfrage zu.", submit:"Immobilie unverbindlich anbieten", submitting:"Anfrage wird gesendet …", successTitle:"Anfrage erhalten", successText:"Vielen Dank für Ihre Immobilienanfrage. Wir haben Ihre Angaben erhalten und werden uns nach Prüfung persönlich mit Ihnen in Verbindung setzen.", confirmationWarning:"Ihre Anfrage wurde übermittelt. Die Bestätigungsmail konnte jedoch nicht zugestellt werden.", errorTitle:"Versand nicht möglich", errorText:"Ihre Anfrage konnte nicht versendet werden. Bitte versuchen Sie es erneut oder schreiben Sie an office@aureliaestates.de.", requiredError:"Bitte füllen Sie dieses Pflichtfeld aus.", emailError:"Bitte geben Sie eine gültige E-Mail-Adresse ein.", fileError:"Bitte verwenden Sie nur PDF-, JPG-, JPEG- oder PNG-Dateien bis 10 MB." },
  en: { ...base, seoTitle:"Submit a property | Aurelia Grundbesitz", seoDescription:"Submit your property in Germany or Turkey to Aurelia Grundbesitz confidentially and without obligation.", kicker:"Confidential property enquiry", title:"Submit a property", intro:"Send us the key details of your property without obligation. We will review your enquiry confidentially and contact you personally.", countryQuestion:"Where is your property located?", germany:"Germany", turkey:"Turkey", requiredHint:"Fields marked * are required.", firstName:"First name", lastName:"Last name", phone:"Phone number", email:"Email address", location:"Property town / postcode", street:"Street / location", propertyType:"Property type", area:"Living / plot area", units:"Number of units", rooms:"Rooms", yearBuilt:"Year built", rented:"Let?", ownerStatus:"Ownership status", price:"Desired sale price", situation:"Special situation", details:"Further information", province:"Province / city", district:"District / neighbourhood", tapu:"Tapu / proof of ownership available?", ownerCount:"Number of owners", ownerResidence:"Owner's current residence", preferredLanguage:"Preferred language", yes:"Yes", no:"No", files:"Photos and documents", uploadHelp:"PDF, JPG, JPEG or PNG · max. 10 MB per file · up to 10 files", privacy:"I have read the privacy policy and consent to my data being processed for this enquiry.", submit:"Submit property without obligation", submitting:"Sending enquiry …", successTitle:"Enquiry received", successText:"Thank you for your property enquiry. We have received your details and will contact you personally after reviewing them.", confirmationWarning:"Your enquiry was delivered, but the confirmation email could not be delivered.", errorTitle:"Unable to send", errorText:"Your enquiry could not be sent. Please try again or email office@aureliaestates.de.", requiredError:"Please complete this required field.", emailError:"Please enter a valid email address.", fileError:"Please use only PDF, JPG, JPEG or PNG files up to 10 MB.", propertyTypes:["Apartment","Detached house","Apartment building","Land plot","Commercial property","Other"], situations:["Standard sale","Inheritance / community of heirs","Financial burden","Ongoing financing","Foreclosure","Multiple owners","Vacancy","Renovation needed","Difficult tenancy","Other"], ownerStatuses:["Sole owner","Co-owner","Heir / community of heirs","Authorised representative","Other"] },
  tr: { ...base, seoTitle:"Gayrimenkul sunun | Aurelia Grundbesitz", seoDescription:"Almanya veya Türkiye'deki gayrimenkulünüzü gizli ve bağlayıcı olmadan sunun.", kicker:"Gizli gayrimenkul talebi", title:"Gayrimenkul sunun", intro:"Gayrimenkulünüzle ilgili en önemli bilgileri bağlayıcı olmadan gönderin. Talebinizi gizlilikle inceleyip sizinle şahsen iletişime geçeceğiz.", countryQuestion:"Gayrimenkulünüz nerede?", germany:"Almanya", turkey:"Türkiye", requiredHint:"* işaretli alanlar zorunludur.", firstName:"Ad", lastName:"Soyad", phone:"Telefon numarası", email:"E-posta adresi", location:"Gayrimenkulün yeri / posta kodu", street:"Sokak / konum", propertyType:"Gayrimenkul türü", area:"Konut / arsa alanı", units:"Birim sayısı", rooms:"Oda sayısı", yearBuilt:"Yapım yılı", rented:"Kirada mı?", ownerStatus:"Mülkiyet durumu", price:"İstenen satış fiyatı", situation:"Özel durum", details:"Ek bilgiler", province:"İl / şehir", district:"İlçe / mahalle", tapu:"Tapu / mülkiyet belgesi mevcut mu?", ownerCount:"Malik sayısı", ownerResidence:"Malikin mevcut ikamet yeri", preferredLanguage:"Tercih edilen dil", yes:"Evet", no:"Hayır", files:"Fotoğraf ve belgeler", uploadHelp:"PDF, JPG, JPEG veya PNG · dosya başına en fazla 10 MB · en fazla 10 dosya", privacy:"Gizlilik politikasını okudum ve bilgilerimin bu talep için işlenmesini kabul ediyorum.", submit:"Bağlayıcı olmadan sunun", submitting:"Talep gönderiliyor …", successTitle:"Talebiniz alındı", successText:"Gayrimenkul talebiniz için teşekkür ederiz. Bilgilerinizi aldık ve incelemenin ardından sizinle şahsen iletişime geçeceğiz.", confirmationWarning:"Talebiniz iletildi ancak onay e-postası teslim edilemedi.", errorTitle:"Gönderilemedi", errorText:"Talebiniz gönderilemedi. Lütfen tekrar deneyin veya office@aureliaestates.de adresine yazın.", requiredError:"Lütfen bu zorunlu alanı doldurun.", emailError:"Lütfen geçerli bir e-posta adresi girin.", fileError:"Yalnızca 10 MB'a kadar PDF, JPG, JPEG veya PNG kullanın.", propertyTypes:["Daire","Müstakil ev","Apartman","Arsa","Ticari gayrimenkul","Diğer"], situations:["Normal satış","Miras / miras ortaklığı","Mali yük","Devam eden finansman","İcra / cebri satış","Birden fazla malik","Boş durumda","Tadilat gerekiyor","Zor kiracı durumu","Diğer"], ownerStatuses:["Tek malik","Hissedar","Mirasçı / miras ortaklığı","Vekil","Diğer"] },
  nl: {} as PropertyOfferCopy, it: {} as PropertyOfferCopy, es: {} as PropertyOfferCopy, fr: {} as PropertyOfferCopy,
};

propertyOfferCopy.nl = { ...propertyOfferCopy.en, title:"Vastgoed aanbieden", kicker:"Vertrouwelijke vastgoedaanvraag", intro:"Stuur ons vrijblijvend de belangrijkste gegevens over uw vastgoed. Wij beoordelen uw aanvraag vertrouwelijk en nemen persoonlijk contact met u op.", countryQuestion:"Waar bevindt uw vastgoed zich?", germany:"Duitsland", turkey:"Turkije", requiredHint:"Velden met * zijn verplicht.", firstName:"Voornaam", lastName:"Achternaam", phone:"Telefoonnummer", email:"E-mailadres", location:"Plaats / postcode van het vastgoed", street:"Straat / ligging", propertyType:"Type vastgoed", area:"Woon- / perceeloppervlakte", units:"Aantal eenheden", rooms:"Kamers", yearBuilt:"Bouwjaar", rented:"Verhuurd?", ownerStatus:"Eigenaarsstatus", price:"Gewenste verkoopprijs", situation:"Bijzondere situatie", details:"Aanvullende informatie", province:"Provincie / stad", district:"District / wijk", tapu:"Tapu / eigendomsbewijs aanwezig?", ownerCount:"Aantal eigenaren", ownerResidence:"Huidige woonplaats van de eigenaar", preferredLanguage:"Voorkeurstaal", yes:"Ja", no:"Nee", files:"Foto's en documenten", privacy:"Ik heb het privacybeleid gelezen en stem in met de verwerking van mijn gegevens voor deze aanvraag.", submit:"Vastgoed vrijblijvend aanbieden", submitting:"Aanvraag wordt verzonden …", successTitle:"Aanvraag ontvangen", successText:"Dank u voor uw vastgoedaanvraag. Wij hebben uw gegevens ontvangen en nemen na beoordeling persoonlijk contact met u op.", confirmationWarning:"Uw aanvraag is verzonden, maar de bevestigingsmail kon niet worden bezorgd.", errorTitle:"Verzenden niet mogelijk", errorText:"Uw aanvraag kon niet worden verzonden. Probeer het opnieuw of mail office@aureliaestates.de.", requiredError:"Vul dit verplichte veld in.", emailError:"Vul een geldig e-mailadres in.", fileError:"Gebruik alleen PDF-, JPG-, JPEG- of PNG-bestanden tot 10 MB.", propertyTypes:["Appartement","Eengezinswoning","Meergezinswoning","Perceel","Bedrijfspand","Overig"], situations:["Normale verkoop","Erfenis / gemeenschap van erfgenamen","Financiële belasting","Lopende financiering","Executieveiling","Meerdere eigenaren","Leegstand","Renovatie nodig","Moeilijke huursituatie","Overig"], ownerStatuses:["Enige eigenaar","Mede-eigenaar","Erfgenaam / erfgenamengemeenschap","Gemachtigde","Overig"] };
propertyOfferCopy.it = { ...propertyOfferCopy.en, title:"Proponi un immobile", kicker:"Richiesta immobiliare riservata", intro:"Inviateci senza impegno i dati principali del vostro immobile. Esamineremo la richiesta con riservatezza e vi contatteremo personalmente.", countryQuestion:"Dove si trova il vostro immobile?", germany:"Germania", turkey:"Turchia", requiredHint:"I campi contrassegnati con * sono obbligatori.", firstName:"Nome", lastName:"Cognome", phone:"Telefono", email:"E-mail", location:"Località / CAP dell'immobile", street:"Via / ubicazione", propertyType:"Tipo di immobile", area:"Superficie abitabile / terreno", units:"Numero di unità", rooms:"Locali", yearBuilt:"Anno di costruzione", rented:"Locato?", ownerStatus:"Stato della proprietà", price:"Prezzo di vendita desiderato", situation:"Situazione particolare", details:"Ulteriori informazioni", province:"Provincia / città", district:"Distretto / quartiere", tapu:"Tapu / prova di proprietà disponibile?", ownerCount:"Numero di proprietari", ownerResidence:"Residenza attuale del proprietario", preferredLanguage:"Lingua preferita", yes:"Sì", no:"No", files:"Foto e documenti", privacy:"Ho letto l'informativa sulla privacy e acconsento al trattamento dei dati per questa richiesta.", submit:"Proponi l'immobile senza impegno", submitting:"Invio in corso …", successTitle:"Richiesta ricevuta", successText:"Grazie per la richiesta. Abbiamo ricevuto i dati e vi contatteremo personalmente dopo averli esaminati.", confirmationWarning:"La richiesta è stata inviata, ma l'e-mail di conferma non è stata recapitata.", errorTitle:"Invio non riuscito", errorText:"Non è stato possibile inviare la richiesta. Riprova o scrivi a office@aureliaestates.de.", requiredError:"Compilare questo campo obbligatorio.", emailError:"Inserire un indirizzo e-mail valido.", fileError:"Utilizzare solo file PDF, JPG, JPEG o PNG fino a 10 MB.", propertyTypes:["Appartamento","Casa unifamiliare","Edificio plurifamiliare","Terreno","Immobile commerciale","Altro"], situations:["Vendita ordinaria","Eredità / comunione ereditaria","Onere finanziario","Finanziamento in corso","Asta giudiziaria","Più proprietari","Sfitto","Da ristrutturare","Locazione difficile","Altro"], ownerStatuses:["Proprietario unico","Comproprietario","Erede / comunione ereditaria","Delegato","Altro"] };
propertyOfferCopy.es = { ...propertyOfferCopy.en, title:"Ofrecer un inmueble", kicker:"Consulta inmobiliaria confidencial", intro:"Envíenos sin compromiso los datos principales de su inmueble. Revisaremos su consulta confidencialmente y nos pondremos en contacto personalmente.", countryQuestion:"¿Dónde se encuentra su inmueble?", germany:"Alemania", turkey:"Turquía", requiredHint:"Los campos con * son obligatorios.", firstName:"Nombre", lastName:"Apellidos", phone:"Teléfono", email:"Correo electrónico", location:"Localidad / código postal", street:"Calle / ubicación", propertyType:"Tipo de inmueble", area:"Superficie habitable / parcela", units:"Número de unidades", rooms:"Habitaciones", yearBuilt:"Año de construcción", rented:"¿Alquilado?", ownerStatus:"Situación de propiedad", price:"Precio de venta deseado", situation:"Situación especial", details:"Más información", province:"Provincia / ciudad", district:"Distrito / barrio", tapu:"¿Tapu / prueba de propiedad disponible?", ownerCount:"Número de propietarios", ownerResidence:"Residencia actual del propietario", preferredLanguage:"Idioma preferido", yes:"Sí", no:"No", files:"Fotos y documentos", privacy:"He leído la política de privacidad y acepto el tratamiento de mis datos para esta consulta.", submit:"Ofrecer inmueble sin compromiso", submitting:"Enviando consulta …", successTitle:"Consulta recibida", successText:"Gracias por su consulta inmobiliaria. Hemos recibido sus datos y nos pondremos en contacto personalmente después de revisarlos.", confirmationWarning:"Su consulta se ha enviado, pero no se pudo entregar el correo de confirmación.", errorTitle:"No se pudo enviar", errorText:"No se pudo enviar su consulta. Inténtelo de nuevo o escriba a office@aureliaestates.de.", requiredError:"Complete este campo obligatorio.", emailError:"Introduzca un correo electrónico válido.", fileError:"Utilice solo archivos PDF, JPG, JPEG o PNG de hasta 10 MB.", propertyTypes:["Piso","Casa unifamiliar","Edificio plurifamiliar","Terreno","Inmueble comercial","Otro"], situations:["Venta normal","Herencia / comunidad hereditaria","Carga financiera","Financiación vigente","Subasta judicial","Varios propietarios","Vacío","Necesita reforma","Arrendamiento difícil","Otro"], ownerStatuses:["Propietario único","Copropietario","Heredero / comunidad hereditaria","Apoderado","Otro"] };
propertyOfferCopy.fr = { ...propertyOfferCopy.en, title:"Proposer un bien immobilier", kicker:"Demande immobilière confidentielle", intro:"Envoyez-nous sans engagement les principales informations sur votre bien. Nous examinerons votre demande en toute confidentialité et vous contacterons personnellement.", countryQuestion:"Où se trouve votre bien immobilier ?", germany:"Allemagne", turkey:"Turquie", requiredHint:"Les champs marqués * sont obligatoires.", firstName:"Prénom", lastName:"Nom", phone:"Téléphone", email:"Adresse e-mail", location:"Ville / code postal du bien", street:"Rue / emplacement", propertyType:"Type de bien", area:"Surface habitable / terrain", units:"Nombre d'unités", rooms:"Pièces", yearBuilt:"Année de construction", rented:"Loué ?", ownerStatus:"Statut du propriétaire", price:"Prix de vente souhaité", situation:"Situation particulière", details:"Informations complémentaires", province:"Province / ville", district:"District / quartier", tapu:"Tapu / justificatif de propriété disponible ?", ownerCount:"Nombre de propriétaires", ownerResidence:"Résidence actuelle du propriétaire", preferredLanguage:"Langue préférée", yes:"Oui", no:"Non", files:"Photos et documents", privacy:"J'ai lu la politique de confidentialité et j'accepte le traitement de mes données pour cette demande.", submit:"Proposer le bien sans engagement", submitting:"Envoi de la demande …", successTitle:"Demande reçue", successText:"Merci pour votre demande immobilière. Nous avons reçu vos informations et vous contacterons personnellement après examen.", confirmationWarning:"Votre demande a été envoyée, mais l'e-mail de confirmation n'a pas pu être livré.", errorTitle:"Envoi impossible", errorText:"Votre demande n'a pas pu être envoyée. Réessayez ou écrivez à office@aureliaestates.de.", requiredError:"Veuillez remplir ce champ obligatoire.", emailError:"Veuillez saisir une adresse e-mail valide.", fileError:"Utilisez uniquement des fichiers PDF, JPG, JPEG ou PNG jusqu'à 10 Mo.", propertyTypes:["Appartement","Maison individuelle","Immeuble collectif","Terrain","Bien commercial","Autre"], situations:["Vente normale","Succession / indivision","Charge financière","Financement en cours","Vente aux enchères judiciaire","Plusieurs propriétaires","Vacance","Rénovation nécessaire","Location difficile","Autre"], ownerStatuses:["Propriétaire unique","Copropriétaire","Héritier / indivision","Mandataire","Autre"] };

type PropertyOfferSeo = Pick<PropertyOfferCopy, "seoTitle" | "seoDescription" | "germanyImageAlt" | "turkeyImageAlt">;

const seoAndAlts: Record<Language, PropertyOfferSeo> = {
  de: { seoTitle: "Immobilie anbieten | Aurelia Grundbesitz", seoDescription: "Bieten Sie Aurelia Grundbesitz Ihre Immobilie in Deutschland oder der Türkei vertraulich und unverbindlich an.", germanyImageAlt: "Wohnimmobilie in Deutschland", turkeyImageAlt: "Immobilie in der Türkei" },
  en: { seoTitle: "Submit a property | Aurelia Grundbesitz", seoDescription: "Submit your property in Germany or Turkey to Aurelia Grundbesitz confidentially and without obligation.", germanyImageAlt: "Residential property in Germany", turkeyImageAlt: "Property in Turkey" },
  nl: { seoTitle: "Vastgoed aanbieden | Aurelia Grundbesitz", seoDescription: "Bied uw vastgoed in Duitsland of Turkije vertrouwelijk en vrijblijvend aan bij Aurelia Grundbesitz.", germanyImageAlt: "Woonvastgoed in Duitsland", turkeyImageAlt: "Vastgoed in Turkije" },
  it: { seoTitle: "Proponi un immobile | Aurelia Grundbesitz", seoDescription: "Proponete ad Aurelia Grundbesitz il vostro immobile in Germania o in Turchia, con riservatezza e senza impegno.", germanyImageAlt: "Immobile residenziale in Germania", turkeyImageAlt: "Immobile in Turchia" },
  es: { seoTitle: "Ofrecer un inmueble | Aurelia Grundbesitz", seoDescription: "Ofrezca su inmueble en Alemania o Turquía a Aurelia Grundbesitz de forma confidencial y sin compromiso.", germanyImageAlt: "Inmueble residencial en Alemania", turkeyImageAlt: "Inmueble en Turquía" },
  tr: { seoTitle: "Gayrimenkul sunun | Aurelia Grundbesitz", seoDescription: "Almanya veya Türkiye'deki gayrimenkulünüzü gizli ve bağlayıcı olmadan sunun.", germanyImageAlt: "Almanya'da konut gayrimenkulü", turkeyImageAlt: "Türkiye'de gayrimenkul" },
  fr: { seoTitle: "Proposer un bien immobilier | Aurelia Grundbesitz", seoDescription: "Proposez votre bien en Allemagne ou en Turquie à Aurelia Grundbesitz, en toute confidentialité et sans engagement.", germanyImageAlt: "Bien résidentiel en Allemagne", turkeyImageAlt: "Bien immobilier en Turquie" },
};

(Object.keys(seoAndAlts) as Language[]).forEach((lang) => {
  Object.assign(propertyOfferCopy[lang], seoAndAlts[lang]);
});
